### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Sonya21** [brichard19/BitCrack#1]
how to use the -r, --range parameter ,show an example

**Comment by brichard19** [comment]
Hi Sonya,

There was a bug with the -r, --range option. It is fixed in the latest build.

-r, --range specifies the number of keys to search

e.g: if you want to search only 1 billion keys:

KeyFinder.exe -r 1000000000  12WdyUdtZDLvi6cS39yso9HQREhBroNY9s

It will stop after 1,000,000,000 keys

**Comment by Sonya21** [comment]
he finds only the uncompressed Bitcoin Address . now almost all the addresses of the Bitcoin Address Compressed format.

**Comment by Sonya21** [comment]
I have a very good plan of action. it will bring great profits .we can talk anonymously, write to me in jabber(Extensible Messaging and Presence Protocol)    raylite@jabber.se

**Comment by brichard19** [comment]
Hi Sonya,

Both compressed and uncompressed addresses are now supported. Compression is on by default. Use -c for compressed and -u for uncompressed.

Sorry, I am not interested in profits. But if you like this project and would like to support it, feel free to donate, if you want to.
