### ISSUE TITLE
Long time Initializing...

### ISSUE THREAD

**Issue by adminnu** [brichard19/BitCrack#10]
Actually initialization takes a very long time. Even on one video card it's about 10 minutes.

**Comment by natedawg469** [comment]
I have noticed that too. Although i find that if u just leave it alone for 15- 20 mins or longer and come back and hit -s it kicks in and starts working.I do not know why but has worked every time for me.

**Comment by bill32767** [comment]
![screenshot 6](https://user-images.githubusercontent.com/32314073/43996939-de41a864-9d82-11e8-8fd6-dbe2ce42f679.png)
Hello Richard, nice tool you have develop. Please what could cause the error "BitCrack64.exe has stopped working.......a programme caused the programme to stop working correctly....." Please help me with ideas.... Thanks.

**Comment by brichard19** [comment]
GPU initialization is in latest release.
