### ISSUE TITLE
what is generating starting points

### ISSUE THREAD

**Issue by gsngsn123** [brichard19/BitCrack#100]
what is generating starting keys how its work? how can i increase is it usefull

**Comment by brichard19** [comment]
The program works by repeatedly adding the basepoint and then hashing to get the address. The search is done in parallel on the GPU, so each thread needs to have a different starting position in the keyspace. 
That is what is happening during 'generating starting points': each thread is being initialized with `kG, (k+1)G, (k+2)...(k+n)G`.
