### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by asam007** [brichard19/BitCrack#102]
Everytime I attempt to compile it gives me the output

util.cpp: In function ‘std::string util::getExeDirectory()’:                                                                                                                                     util.cpp:298:9: error: ‘readlink’ was not declared in this scope                                                                                                                                          readlink("/proc/self/exe", buf, sizeof(buf));                                                                                                                                                    ^~~~~~~~                                                                                                                                                                                util.cpp:298:9: note: suggested alternative: ‘unlink’                                                                                                                                                     readlink("/proc/self/exe", buf, sizeof(buf));                                                                                                                                                    ^~~~~~~~                                                                                                                                                                                         unlink
--
make[1]: *** [Makefile:6: all] Error 1                                                                                                                                                           make[1]: Leaving directory '/cygdrive/c/BitCrack-0.22/util'                                                                                                                                      make: *** [Makefile:98: dir_util] Error 2
--

**Comment by brichard19** [comment]
0.22 is out of date. Please try to build the latest code.
