### ISSUE TITLE
ubuntu 16.04 and 18.04 

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#104]
opencl compile error on both OS

![screenshot from 2018-12-04 21-15-57](https://user-images.githubusercontent.com/42878992/49456241-8fc1bc00-f80a-11e8-9dad-65f682f0b63e.png)

**Comment by hamnaz** [comment]
![screenshot from 2018-12-04 21-16-50](https://user-images.githubusercontent.com/42878992/49456266-9c461480-f80a-11e8-8172-33e59c12fd03.png)

**Comment by hamnaz** [comment]
above i use ubuntu 16.04 + cuda 8.0 + gtx460
compute set 30 + 8.0 path in make file

![1](https://user-images.githubusercontent.com/42878992/49464352-7a558d80-f81c-11e8-88f4-717faa2033de.jpg)
![2](https://user-images.githubusercontent.com/42878992/49464353-7a558d80-f81c-11e8-969f-d3441d4e5f36.jpg)
![3](https://user-images.githubusercontent.com/42878992/49464354-7aee2400-f81c-11e8-8b16-915116788622.jpg)
![4](https://user-images.githubusercontent.com/42878992/49464355-7aee2400-f81c-11e8-8b02-ad385ab25d13.jpg)

**Comment by hamnaz** [comment]
applied compute 21 and 20 too, but cubitcrack created, but synbolic error

**Comment by hamnaz** [comment]
instead of warning messages, i dont know i try many settings which one worked, now WORKING
cubitcrack working
1 issue left
when useing command
./cuBitCrack --keyspace 80000000:ffffffff 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
cuda work on 20.5 mkey/s
 
when useing input file ( 3 difrent file tried, with 1m address, 10m address, 18m address
all time speed at 10 mkey/s

i repeated these procedure again and again, but after load any file speed  reduce to 50%
i think need to optimized bloom filter

**Comment by brichard19** [comment]
> 1m address, 10m address, 18m address
all time speed at 10 mkey/s

That's expected. When searching for a small number of keys, the keys are kept in the very fast GPU cache memory. The bloom filter sits in the GPU RAM which is much slower.

**Comment by Roundtree-Larry** [comment]
Please How did you Build it in Ubuntu ? I tried it but all error.
