### ISSUE TITLE
i dont know address parsing pls post addresses google drive link 

### ISSUE THREAD

**Issue by gsngsn123** [brichard19/BitCrack#109]
i dont know address parsing pls post addresses google drive link

**Comment by Elecman** [comment]
https://github.com/bitcoinhush/bitcoinhush/tree/new_master/airdrop

**Comment by Elecman** [comment]
use google.com)

**Comment by gsngsn123** [comment]
iam asking for bulk addresses text file

**Comment by hamnaz** [comment]
these are paid services contact solarbusinesspk@gmail.com

**Comment by ogronome** [comment]
Parsing all blockchain requires a beefy server with 96GB of RAM.
Also many public parsers broke on segwit.
So you probably do not want to bother and need just a file.

That's with 87 thousand addresses. 
Checked a week ago for stale records
[http://80.211.89.91/87k](url)
many of them are old (uncompressed)
but some big modern wallets are also included.

**Comment by gsngsn123** [comment]
got it thank u somuch
