### ISSUE TITLE
strange bitcoins

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#112]
during work i found key, it says it have transactions
i search at address blockchain, its says 0 in-out
webbtc says 4 transaction
btc.com says 2 transaction
1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q

https://webbtc.com/address/1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q
https://btc.com/1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q
https://www.blockchain.com/btc/address/1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q

even i found a address which balance is  -1
every in out have balance or 0, could not be -1
mean some secrets behind this crypto

**Comment by Coinpiet** [comment]
wow cool in which space you found in 59 bit ? 

do you search with compressed and uncompressed settings ? 

and what BTC address list do you have ?

**Comment by hamnaz** [comment]
my search setting always both 
i have complete list of current address have balance, i am collecting by pay to some one from last 3 years, from last 5 month i able to parse complete address list with balance, every month, once i need to pay for machine fee for use to run parser blockchain, and collect fresh data

![imag0021](https://user-images.githubusercontent.com/42878992/49946546-051b4400-ff11-11e8-8374-ca5a2ff1a271.jpg)
![imag0024](https://user-images.githubusercontent.com/42878992/49946547-05b3da80-ff11-11e8-805b-40bb72686517.jpg)
![111imag0029](https://user-images.githubusercontent.com/42878992/49946682-4e6b9380-ff11-11e8-8eb5-dff34254dead.jpg)

**Comment by hamnaz** [comment]
and an other research, everyone on crypto developer, account could not be in minus, but 3 address i know in bitcoin network work in minus :)
shown here 1 for your all people refrence
https://www.blockchain.com/btc/address/1Fr8qEa7vcwJikeW9q6thaYZPacGY5CQAb

you will see payment come and go, but mostly you will see account in minus after all spent
![1234](https://user-images.githubusercontent.com/42878992/49947397-fafa4500-ff12-11e8-99e0-41fd9d39fe74.jpg)

**Comment by Coinpiet** [comment]
Wow OK this is great can you mabey share this address list?
How much BTC you already found?

**Comment by Coinpiet** [comment]
Do you run your parser on extern server?

**Comment by hamnaz** [comment]
yes
8 vcpu and 256gb ram

**Comment by Coinpiet** [comment]
Can you share this address file?

**Comment by Coinpiet** [comment]
And how much wallets have you found already?

**Comment by hamnaz** [comment]
https://www.blockchain.com/btc/address/1CzcfKwr4xh4wJ3ePDE4UU8J6RZNSrcuVS

here 2 transaction with 0.00 in out

**Comment by Coinpiet** [comment]
Wow I mean I never thought that people can find so many keys.
How many machines do you have?
And in which search space are you only in the higher ones I think?

**Comment by Coinpiet** [comment]
And all with this one big address list?

**Comment by Coinpiet** [comment]
and how long does it take for this results ? 

how much power do you have man ? :0

**Comment by Dragoula** [comment]
Coinpiet, the 84k add file you're using are from dormant addresses? If so, dormant for how long? 1 year ? 2?

**Comment by hamnaz** [comment]
total address in use are 23m, 
start 1 aprox 19m
start 3 aprox 3m
start bc1 aprox 1m
i have 5 machines and four old GPU cards
90% money i wasted in fee for remote servers with heavy GPU like tesla P100, tesla v100
my 2 machines can install 40 GPU, but i dont have money for buy tesla p100, if some one like donate me tesla P100, i will say thank you, with next winnign tip :)
i could not say about keyspace, must say, 
Probability and Possibility always somewhere, try to find with you LUCK

**Comment by Coinpiet** [comment]
Dragoula we checked this file and most ofthe addresses where dead so last aktivity was in 2009 and 2011 until 14.

**Comment by hamnaz** [comment]
just found newly created key https://www.blockchain.com/btc/address/144kpY4giqVM1X1U7Kq1QxHhrYfS7QFk8b

**Comment by Coinpiet** [comment]
i have installed brainflayer at the moment 

but i havent a blf file 

how cani get that ?

**Comment by Coinpiet** [comment]
omg great how you find that so fast ? 
with brainflayer

**Comment by Dragoula** [comment]
Did you find it with brainflayer or bitcrack?

**Comment by Coinpiet** [comment]
í have only a 5 GPU rig and this one works with Bitcrack 

and i have 2 AMD rx 480 

and one i7  and one intel celeron

**Comment by Coinpiet** [comment]
hamnaz can we mabey write email ?

**Comment by hamnaz** [comment]
with brainflayer, its too slow, bc no gpu function inside
bro some time fast like rabit, some time slow with turtle
overall developer is like teacher, who teach us some lesson for take steps into life, and we are students, which can reach at higher to president, but teacher is teacher, like my teacher often said
wise student is father of teacher, but teacher is TEACHER

**Comment by hamnaz** [comment]
[2018-12-14.16:14:15] [Info] Initializing GeForce GTX 460
[2018-12-14.16:14:15] [Info] Generating 4,194,304 starting points (160.0MB)
[2018-12-14.16:14:17] [Info] 10.0%
[2018-12-14.16:14:18] [Info] 20.0%
[2018-12-14.16:14:19] [Info] 30.0%
[2018-12-14.16:14:20] [Info] 40.0%
[2018-12-14.16:14:21] [Info] 50.0%
[2018-12-14.16:14:22] [Info] 60.0%
[2018-12-14.16:14:23] [Info] 70.0%
[2018-12-14.16:14:23] [Info] 80.0%
[2018-12-14.16:14:24] [Info] 90.0%
[2018-12-14.16:14:25] [Info] 100.0%
[2018-12-14.16:14:25] [Info] Done
[2018-12-14.16:14:25] [Info] Loading addresses from '11full.txt'
[2018-12-14.16:16:08] [Info] 19,788,169 addresses loaded (377.4MB)
[2018-12-14.16:16:09] [Info] Allocating bloom filter (512.0MB)
[2018-12-14.16:16:13] [Info] Allocating bloom filter (512.0MB)
[2018-12-14.16:16:17] [Info] Found key for address '144kpY4giqVM1X1U7Kq1QxHhrYfS7QFk8b'. Written to 'output.txt'
GeForce GTX 460  951/964MB | 19788168 targets 13.49 MKey/s (26,268,925,952 total) [00:33:01]

**Comment by Coinpiet** [comment]
Can you be my teacher teacher?

Wow this is really great

**Comment by hamnaz** [comment]
i am student, brichard and respectively every developer is our teacher

**Comment by Coinpiet** [comment]
Yeah I understand but we can write and mabey help us together or is this mabey a head on head fight who found is winner.
No I think we should help us together. 
Are you student of computer science?

**Comment by Coinpiet** [comment]
You mean you found with brainflayer because bitcrack is to slow?
I thought bc is fastest

**Comment by Coinpiet** [comment]
I saw you say you found lots of wallets.
these was all dead ones?

**Comment by hamnaz** [comment]
no one dead, all had coins, every month i use fresh list
i am not CS student :)
i have 3 engineering degree's, and masters in CS from 1994. when first computer launch i were player in assembly n cat dos level, i were reverse engineer in software industry, all assembler, computer  languages cross from my hand before 1990, actually from last 5 year i were paralyze, and unable to do anything, this year i just jump to recover my lost address and amounts which i earn more then 150000 btc in 2010,2011,2012, against my software sales and E-marketing, my children formated my hdd and sale old pc;s bring new pc;s, in my illness days,this year i recovered 80%, and come to know, lot of happen last year, and still now in good, but no records now , for recovery my lost i am working, hope i will recover soon

**Comment by Coinpiet** [comment]
Wow OK nice to hear that hamnaz. 
Omg 150000 btc that's a lot of money man do you have the wallet dat? 
And what is with ndv vanitygen?
I use this fork is this not so good?

**Comment by Coinpiet** [comment]
no i mean with dead addresses that the coin are there since 2011 or so

**Comment by Coinpiet** [comment]
can i work with the samr7 vanitygen with my address list 

or what should i do with the pattern this dont help me to find the puzzel or any addresses from my list.

hamnaz can you please explain me

**Comment by hamnaz** [comment]
rusty blockparser

**Comment by Coinpiet** [comment]
Hey thanks
Can you please also answer my previous questions?

**Comment by hamnaz** [comment]
follow commands at github rusty blockparser

**Comment by Coinpiet** [comment]
Oh man can we write bit more?
What is the best option after I have the whole addresses with funds?

**Comment by hamnaz** [comment]
vanitygen brainflayer BitCrack, all you need have address list

**Comment by Coinpiet** [comment]
Yeah but I only can use the address list with vanitygen with the ndv fork or not?

**Comment by hamnaz** [comment]
yes you can use address list

**Comment by Coinpiet** [comment]
With all vanitygen forks?
How I use address list with samr7 fork?

**Comment by Coinpiet** [comment]
i use ubunut bash on win 10 and i install the rusty blockpareser there but i cannot get the file from my hdd with the blocks 

`./rusty-blockparser -r -t7 unspentcsvdump C:/Users/Peter/De
sktop/BLK
[23:04:29] ERROR - main: Couldn't initialize csvdump with folder: `C:/Users/Peter/Desktop/BLK` I/O Error: No such file or directory (os error 2)`

**Comment by Coinpiet** [comment]
but i have it there

**Comment by Coinpiet** [comment]
`./rusty-blockparser -r -t7 -d /mnt/c/Users/Peter/Desktop/BLK csvdump
error: The following required arguments were not provided:
    <dump-folder>`

**Comment by Coinpiet** [comment]
ok i have it now but the unspentcsvdump is a fail there also 0 zero balances in the csv file

**Comment by Coinpiet** [comment]
is the Bitcoin-core Blockchain buggy ?

**Comment by RB61** [comment]
Hi Hamnaz,
Do you know of any oclvanitygen fork which can take full addresses? the one I have takes at most 33 characters (gives error for 34).
Also, I could show you where to change code to bitmask headdress. But maybe you already know how to do that :).

**Comment by hamnaz** [comment]
only samr vanitygen work with seed and random
other all folk including ndv start from 01 to series, like bitcrack but buggy, you can test 32 btc bountry ( 255 addresses), only ndv takes full addresses, (33 and 34 length address) remove 27 to 32 length addreses
other fork you need filter pattern from address list

rusty block parser required 1tb free space on hdd, and 256gb ram and no swap
then it work perfect, other you will receive errors

**Comment by RB61** [comment]
I use chainstate, it works perfectly. I can parse the whole blockchain with only 32Gb ram (with swap space). It does not take very long. You get all btc addresses sorted from high balance to zero balance (less than 1Gb file) 22 365 155 addresses as of yesterday ;)

**Comment by RB61** [comment]
Of course, I sort the list and remove addresses starting with "3" and also starting with "bc1"

**Comment by RB61** [comment]
I forgot to mention that I remove also zero balance addresses.

**Comment by Coinpiet** [comment]
OK i have 16 GB RAM and I make it that I copy mabey 15 blk files in one dir. and parse this 15 files and at these 15 files I got 1.6 m unspent addresses but there are also zero balances. And yes I have 2 tb ;)

**Comment by Coinpiet** [comment]
RB61 yeah but i thought that this parser only parse addresses with funds and the zero balance are not in the output file

**Comment by Coinpiet** [comment]
i tryed to parse it with this parser https://github.com/znort987/blockparser but i have only the BLK.dat files and not the /.bitcoin data

and i dont know how to build the chainstate can you mabey explain me. ?

**Comment by Coinpiet** [comment]
RB61 i have the BTC core client v0.17.1 does it work with chainstate too ? 

and how can i run my blk files throw  chainstate ?

**Comment by RB61** [comment]
You are right. From what I understand, chainstate does not use blk files but uses ldb files. that's why it is faster ... the blk files are more that 212Gb of size and the ldb files are 2.Gb.

**Comment by RB61** [comment]
I've changed to chainstate because blockparser uses a lot more memory and disque space. I could never parse the whole blockchain.

**Comment by Coinpiet** [comment]
i try at the moment with the rusty blockparser and i take one 1 gb of ram but the parser write at the moment 391436 Blocks added to index

**Comment by Coinpiet** [comment]
RB61 i have build the chainstate but can you please tell me how to use it right and how i can get the ldb filles `?

**Comment by Coinpiet** [comment]
Hamnaz mabey it will work also with 16 GB RAM because I have already 2/3 of work and it uses 14gb ram.
Now I am excited what I get with the unspentcsvdump file

**Comment by Coinpiet** [comment]
I don't have the ./ Bitcoin folder I use the Ubuntu bash system on win 10 and I only have the blk files from the btc core gui

**Comment by RB61** [comment]
This may help 
https://en.bitcoinwiki.org/wiki/Data_directory

**Comment by Coinpiet** [comment]
Yeah but I have all on a hard drive

**Comment by Coinpiet** [comment]
i dont have Bitcoin in Appdata

**Comment by Coinpiet** [comment]
`~/chainstate$` cat /tmp/cs.errors
chainstate: chainstate.cc:82: int main(int, char**): Assertion status.ok()' failed.`

i have this problem but i changed all what the guys were written at the issue

**Comment by Coinpiet** [comment]
i installed this leveldb https://github.com/google/leveldb

but i dont know how to start 

sudo cp -Rp ~/mnt/e/BitcoinFullnode/Blockchain/chainstate  state
cp: Aufruf von stat für '**/home/PETERPC/**mnt/e/BitcoinFullnode/Blockchain/chainstate' nicht möglich: Datei oder Verzeichnis nicht gefunden

i dont know why /home/PETERPC is everytime there

**Comment by gmk89** [comment]
> during work i found key, it says it have transactions
> i search at address blockchain, its says 0 in-out
> webbtc says 4 transaction
> btc.com says 2 transaction
> 1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q
> 
> https://webbtc.com/address/1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q
> https://btc.com/1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q
> https://www.blockchain.com/btc/address/1zdCLiqBrhZ6CbxY8FEX61Vo2TfP4vn4Q
> 
> even i found a address which balance is -1
> every in out have balance or 0, could not be -1
> mean some secrets behind this crypto

Having a negative balance indicates a 'double spend'

**Comment by biggiplace654** [comment]
> Do you run your parser on extern server?
