### ISSUE TITLE
stride

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#115]
i have tested similar more then 200 commands with different keys , all result same, mean its not increment, its skip in hexdec 64 char, and start last row n stop
mean
start to end key shown useless here
it work only under
from xxxxx33333333333333333333333333333333333333333333333333333333333
to fffff33333333333333333333333333333333333333333333333333333333333
but no key found
cross i check difrent way and found only it will work where last digit is 1
mean
from xxxxx33333333333333333333333333333333333333333333333333333333331
to fffff33333333333333333333333333333333333333333333333333333333331

note : X is just for refrence, acutal strid is after X,

**Comment by hamnaz** [comment]
in my view how --increment
program should have start and end key must fill, (no pre define)
example
start 1000000000000000000000000000000000000000000000000000000000000000
end 1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
--increment 1000
convert number of key to hex
first key will be
1000000000000000000000000000000000000000000000000000000000000000 + 03E7 (1000)
10000000000000000000000000000000000000000000000000000000000003E7
2nd key will be
10000000000000000000000000000000000000000000000000000000000003E7 + 03E7 (1000)
10000000000000000000000000000000000000000000000000000000000007CE

third key will be
10000000000000000000000000000000000000000000000000000000000007CE + 03E7 (1000)
1000000000000000000000000000000000000000000000000000000000000BB5

same expand each key hex value add in previous key

like number of keys
example
--increment 1693 hex value is 069c

**Comment by Coinpiet** [comment]
sorry for that but i really dont know.

i have now alll balanced addresses the file have 22 MIo addresses in but there are also multi signature wallets and wallets starting with `ab` or ´bc`  how can i delet these addresses with a filter 

i have tryed ultraedit and emEditor but i dont find the solution 

mabey you can help hamnaz ?

**Comment by Coinpiet** [comment]
hamnaz i have now my 18 mio file list with all fresh addresses. 

so my question is how is your strategy that you found so much addresses ?

**Comment by Coinpiet** [comment]
i wanted to start brainfalyer too but this error come after i wnat to start it 

./brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b FundsAddresses.blf
failed to open bloom filter 'FundsAddresses.blf': Incorrect file size

**Comment by Coinpiet** [comment]
should i make my 18 mio address list with all addresses starting with "1" to hex do use brainflayer ? 

btw you can download the whole address lists for free here i donwloaded it yesterday for free

https://balances.syndevio.com

**Comment by hamnaz** [comment]
> should i make my 18 mio address list with all addresses starting with "1" to hex do use brainflayer ?
> 
> btw you can download the whole address lists for free here i donwloaded it yesterday for free
> 
> https://balances.syndevio.com

bro for discus other issue, pls create issue with what wy where how  about address file uses in bitcrack bainflayer and vanitygen etc

this issue is about Stride, let other and developer consider/discus on this issue
thankx

**Comment by hamnaz** [comment]
easy to chat in common " strange bitcoins " or email solarbusinesspk@gmail.com

**Comment by Coinpiet** [comment]
thanks a lot man :)

**Comment by Coinpiet** [comment]
i wrote you an email.

**Comment by hamnaz** [comment]
coinpiet pls remove your post from this issue,

**Comment by hamnaz** [comment]
Key:
1JbxysvKJvAWKrfxEX2ThvHMDxmyBGYS6q
1234533333333333333333333333333333333333333333333333333333333333
command ( 59 times 3)
./cuBitCrack 1JbxysvKJvAWKrfxEX2ThvHMDxmyBGYS6q --stride 33333333333333333333333333333333333333333333333333333333333

result

root@i3-6100:/home/chawla/1/BitCrack/bin# ./cuBitCrack 1JbxysvKJvAWKrfxEX2ThvHMDxmyBGYS6q --stride 33333333333333333333333333333333333333333333333333333333333
[2018-12-09.03:21:48] [Info] Compression: compressed
[2018-12-09.03:21:48] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-12-09.03:21:48] [Info] Ending at: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140
[2018-12-09.03:21:48] [Info] Counting by: 0000033333333333333333333333333333333333333333333333333333333333
[2018-12-09.03:21:48] [Info] Initializing GeForce GTX 460
[2018-12-09.03:21:48] [Info] Generating 262,144 starting points (10.0MB)
[2018-12-09.03:21:49] [Info] 10.0%
[2018-12-09.03:21:49] [Info] 20.0%
[2018-12-09.03:21:49] [Info] 30.0%
[2018-12-09.03:21:49] [Info] 40.0%
[2018-12-09.03:21:50] [Info] 50.0%
[2018-12-09.03:21:50] [Info] 60.0%
[2018-12-09.03:21:50] [Info] 70.0%
[2018-12-09.03:21:50] [Info] 80.0%
[2018-12-09.03:21:51] [Info] 90.0%
[2018-12-09.03:21:51] [Info] 100.0%
[2018-12-09.03:21:51] [Info] Done
[2018-12-09.03:21:51] [Info] Reached end of keyspace
root@i3-6100:/home/chawla/1/BitCrack/bin#
