### ISSUE TITLE
Typical Performance on Card

### ISSUE THREAD

**Issue by gmk89** [brichard19/BitCrack#116]
I have an Nvidia GeForce GTX 1050.  When running I use, `-b 5 -t 512 -p 512` I get about 0.87 MKeys/s.  Does this sound about right or a little low?  When I try and increase b,t,p I get errors.

**Comment by PsyShark** [comment]
Download cudaInfo.exe from previous releases and see how many blocks you have (MP)
ID:          0
Name:        GeForce GTX 1070
Capability:  6.1
**MP:          15**
Cores:       1920 (128 per MP)
Memory:      8192MB

**Comment by gmk89** [comment]
Thanks that helps
