### ISSUE TITLE
-r options

### ISSUE THREAD

**Issue by Simkas45** [brichard19/BitCrack#119]
подскажите пожалуйста как заставить bitcrack закрываться после 1000000000 проверенных hex ?
раньше мог реализовать это с помощью команды -r, а теперь как ?

**Comment by PsyShark** [comment]
--keyspace 0000000000000000000000000000000000000000000000000000000000000001:+3B9ACA00
3B9ACA00 - это 1000000000 в 16-ричном

**Comment by Simkas45** [comment]
thank you!
