### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by granula** [brichard19/BitCrack#12]
In my noutbook this progrramm not run

**Comment by natedawg469** [comment]
No one can help you if you do not provide details.

**Comment by bill32767** [comment]
I don't understand. Which details do you want me to provide?

**Comment by granula** [comment]
http://pix.my/IhTtsU
http://pix.my/uB6Qiv

**Comment by granula** [comment]
http://pix.my/goI0jg

**Comment by bill32767** [comment]
I have seen the photos, same problem with mine. Granula, your CPU and GPU
are high yet same problem, what could be the cause and solution?

**Comment by brichard19** [comment]
There's your problem. Unfortunately this project only supports nVudia GPUs at the moment.

I intend to write an OpenCL version in the future, but for now its CUDA only.
