### ISSUE TITLE
Error detecting devices

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [brichard19/BitCrack#121]
@brichard19 get this error while running:

[2018-12-26.12:00:07] [Error] Error detecting devices: CL_UNKNOWN_ERROR

Lib ocl-icd-opencl-dev is installed and test running on 512MB ATI AMD Radeon R4 Graphics

**Comment by dem10** [comment]
> @ brichard19 получить эту ошибку во время работы:
> 
> [2018-12-26.12: 00: 07] [Ошибка] Обнаружение ошибки устройства: CL_UNKNOWN_ERROR
> 
> Lib ocl-icd-opencl-dev установлен и тестируется на 512 МБ ATI AMD Radeon R4 Graphics

I got the same error in Ubuntu and Linux mint(R9 390x).Мay be a problem with the drivers.

**Comment by SatoshiNakamotoBitcoins** [comment]
@dem10 I got this error on Kali Linux and Xubuntu...

**Comment by SatoshiNakamotoBitcoins** [comment]
@dem10 Actually it should work out of the box:


I am updating this for anyone wondering and/or searching the same thing as me.

A few days ago, I ended up buying a laptop with A6-9220 and AMD Radeon R4.
I installed debian testing -> debian unstable. Graphics work out of the box. I have accelerated 2d Desktop (xfce). Drawing/moving of windows (and their contents) isn't laggy. Plus it seems to playback 1080p youtube videos without any real problem.
I haven't tested 3d capabilities, since I am not interested much in them at the moment. My usage is mainly libreoffice and browsing.

I also tested a live cd of Xubuntu 17.10. It also worked out of the box.

As far as I can tell, both used the 'amdgpu' driver. I don't know if that is good or bad. Nor do I know the relationship of this driver with other amd drivers eg radeonsi, ati, radeon etc

**Comment by dem10** [comment]
> @ dem10 На самом деле это должно работать из коробки:
> 
> Я обновляю это для тех, кто интересуется и / или ищет то же самое, что и я.
> 
> Несколько дней назад я закончил тем, что купил ноутбук с A6-9220 и AMD Radeon R4. 
> Я установил тестирование Debian -> Debian нестабильный. Графика работает из коробки. Я ускорил 2d Desktop (xfce). Рисование / перемещение окон (и их содержимого) не запаздывает. Кроме того, кажется, что для воспроизведения видео 1080p YouTube без каких-либо проблем. 
> Я не тестировал 3d-возможности, так как в данный момент я не очень ими заинтересован. Я использую в основном libreoffice и просматриваю.
> 
> Я также протестировал живой CD Xubuntu 17.10. Это также сработало из коробки.
> 
> Насколько я могу судить, оба использовали драйвер 'amdgpu'. Я не знаю, хорошо это или плохо. Также я не знаю отношения этого драйвера с другими драйверами amd, например, radeonsi, ati, radeon и т. Д.

I searched a bit in Google and still probably this driver, here is a similar problem and its solution.
https://rastating.github.io/fixing_cl_unknown_error_in_hashcat_on_ubuntu_16_04_with_nvidia_gpu/

**Comment by dem10** [comment]
> @dem10 I got this error on Kali Linux and Xubuntu...

Of course Linux-Like systems are better in terms of speed but with the drivers they have trouble.And with different versions of Linux change the way drivers are installed.Linux is good for those who understand the development.

**Comment by SatoshiNakamotoBitcoins** [comment]
@dem10 @brichard19 Switcht to Windows...like a charm...

**Comment by Roundtree-Larry** [comment]
I get this problem ,how did you solve it please ?

**Comment by SatoshiNakamotoBitcoins** [comment]
@Roundtree-Larry Hey mate...try it with Windows...download from the releases section...
