### ISSUE TITLE
Really Slow Speeds

### ISSUE THREAD

**Issue by takemetothepub** [brichard19/BitCrack#142]
Hi everyone, I have two computers, one with a gtx 1060 6gig and one with a 980ti.

On both I can only get speeds up to 2.5m/s 

Any ideas where I'm going wrong? 

The specs on the 1060 card are:

ID:               0
Name:        GeForce GTX 1060 6GB
Capability:  6.1
MP:            10
Cores:        1280 (128 per MP)
Memory:    6144MB

Any help for -b -p -t would be great.

**Comment by takemetothepub** [comment]
Screen shot of the gtx 1060 card using stock settings and the info results.

![capture](https://user-images.githubusercontent.com/36158326/52207584-cac98580-2875-11e9-9d5d-a727b9703b6f.JPG)
![capture2](https://user-images.githubusercontent.com/36158326/52207585-cac98580-2875-11e9-838b-196ba15a6edc.JPG)

**Comment by brichard19** [comment]
Looks like you built in Debug mode. Try build in Release mode.

**Comment by takemetothepub** [comment]
YES! Amazing, thank you so much!
