### ISSUE TITLE
cuBitCrack.exe skips private keys on Nvidia Pascal graphics cards - it is out FILE bug

### ISSUE THREAD

**Issue by asmzx** [brichard19/BitCrack#149]
I have generated test list of pairs(btc address - private key) -100000 of random pairs
+ 1000 special pairs with pattern:
C31F31D4BCEF508C1CD1C6B017616490000000000D4162AE96560A0E52B37E5A
C31F31D4BCEF508C1CD1C6B01761649FFFFFFFFFFD4162AE96560A0E52B37E5A
0000000000000000000000000000000000000000100000000000000000000000
On Nvidia 1060 6Gb it takes 03:04:26 and found 883 records, 117 records did not found.
On this 883 records - two records is bad:
1JhDzh8WeSM2KEiwDkwtyNATuSz1VqFs C31F31D4BCEF508C1CD1C6B017616493302B1E4F6D4162AE96560A0E52B37E5A
17NmV4BcTZG7NPutipMBDRQYZkRkdNkK C31F31D4BCEF508C1CD1C6B017616498323F03821D4162AE96560A0E52B37E5A
(the address must be 11JhDzh8WeSM2KEiwDkwtyNATuSz1VqFs and 11JhDzh8WeSM2KEiwDkwtyNATuSz1VqFs - miss one '1' at the beginning)

**Comment by asmzx** [comment]
https://drive.google.com/open?id=1wtG5FxKkyhNs7igv20NbQpVvyMmmi0hG

**Comment by asmzx** [comment]
I can see all miss records in console:

**Comment by asmzx** [comment]
[2019-03-02.00:29:51] [Info] Found key for address '1CxyLzFMBy5XkxGvfNF4WvATKzoetuMiLK'. Written to 'res0.txt'

**Comment by bill32767** [comment]
Hello asmzx,
I have checked both bad/good_pair.TXT contain valid address generated in
serial pamutation. can I get the list of the address (of both
bad/good_pair.TXT) without their private keys so that I will be able to
scan with your pattern to understand the situation better.

**Comment by asmzx** [comment]
add 2 files - onlygood.txt and onlybad.txt

**Comment by asmzx** [comment]
419.35-desktop-win8-win7-64bit-international-whql.exe - correct result
416.34-desktop-win10-64bit-international-whql.exe - wrong result
It is dependent on driver version.
