### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by ejcosti** [brichard19/BitCrack#161]
Trying to compile this on a Mac, what could I be doing wrong?  I had to replace -lOpenCL in various Makefiles with -framework OpenCL
The card I am trying to use is the built in Radeon Pro 560.

ifeq ($(BUILD_OPENCL),1)
	${CXX} -DBUILD_OPENCL -o clKeyFinder.bin ${CPPSRC} ${INCLUDE} -I${OPENCL_INCLUDE} ${CXXFLAGS} ${LIBS} -L${OPENCL_LIB} -lkeyfinder -laddressutil -lsecp256k1 -lcryptoutil -lsecp256k1 -lCLKeySearchDevice -lclutil -framework OpenCL -llogger -lutil -lcmdparse

g++ -o clunittest.bin cltest.cpp cltest.cpp main.cpp  -I/projects/BitCrack/util  -I/projects/BitCrack/AddressUtil  -I/projects/BitCrack/CmdParse  -I/projects/BitCrack/CryptoUtil  -I/projects/BitCrack/KeyFinderLib  -I/projects/BitCrack/CLKeySearchDevice  -I/projects/BitCrack/CudaKeySearchDevice  -I/projects/BitCrack/cudaMath  -I/projects/BitCrack/clUtil  -I/projects/BitCrack/cudaUtil  -I/projects/BitCrack/secp256k1lib  -I/projects/BitCrack/Logger  -I/projects/BitCrack/embedcl -I/Developer/NVIDIA/CUDA-10.1/include -O2 -std=c++11 -DCL_TARGET_OPENCL_VERSION=110 -L/projects/BitCrack/lib -L/Developer/NVIDIA/CUDA-10.1/lib -lclutil -framework OpenCL
Undefined symbols for architecture x86_64:
  "util::toLower(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      cl::CLProgram::CLProgram(cl::CLContext&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in libclutil.a(clContext.o)
      cl::CLProgram::CLProgram(cl::CLContext&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in libclutil.a(clContext.o)
ld: symbol(s) not found for architecture x86_64

**Comment by grr** [comment]
how did you resolve this?
