### ISSUE TITLE
Explanation of the key rate when using a list.

### ISSUE THREAD

**Issue by TheDailySpank** [brichard19/BitCrack#180]
I apologize ahead of time for asking a terribly dumb sounding question, but let's consider 3 scenarios.

1. Address list has 1 address, shows ~240Mkey/s
2. Address list has 100 addresses, shows ~240Mkey/s
3. Address list has 100,000 addresses, shows ~160Mkey/s

Does this mean after one second 
1. 240,000,000
2. 24,000,000,000
3. 16,000,000,000,000
total checks have been made (keys * addresses)

...or does it mean 
1. 240,000,000
2. 240,000,000
3. 160,000,000
addresses have been checked for 1 key each?

Essentially, does having a large list increase the probability of finding a key sooner or is there a point at which having too many addresses simply slow everything down?

**Comment by kaanalican** [comment]
Hello, The workload increases when the number of addresses increases. Seconds falling at speed. It's perfectly normal.
240MKey per second means 240 million addresses have been produced and individually checked with the addresses on the target. Normal is a tremendous speed.

**Comment by TheDailySpank** [comment]
> 240MKey per second means 240 million addresses have been produced and individually checked with the addresses on the target.

So it's key/s * addresses efficient?

**Comment by 1000Bursh** [comment]
Hi.
CUDA® is a parallel computing platform Pollard_s kangaroo-Windows 10 -Ubuntu 18.04 Full Code:
https://github.com/pikachunakopika/Pollard_s-kangaroo
