### ISSUE TITLE
Error every time I try using a .txt list with -i

### ISSUE THREAD

**Issue by rohosalndn** [brichard19/BitCrack#181]
I tried this on several workstations and the program says 'stop working' when loading address.txt file with -i. 

The list  has 100 addresses but I've read here it should work with thousands. It works with around 30 addresses but more than that the program exits. 

I have Nvidia Tesla, 64GB RAM. No other issues and it works without using the list. 

Any suggestions of what can cause this? It's a text file, each address on separate line. 

Thanks!

**Comment by kaanalican** [comment]
There is a problem with the lines in your address file. Or there is a problem with the -b -t -p values. There's no other way.

**Comment by rohosalndn** [comment]
-b -t -p values are at default, haven't changed any The list is fine I think, as it works with fewer lines. Perhaps one of the addresses / line is being rejected for some reason.

**Comment by rohosalndn** [comment]
OK, a silly question: This is not suppose to work with addressees starting with 3, right? Just the ones starting with 1? Maybe that's the issue with my list. Thanks.

**Comment by kaanalican** [comment]
I work with 20,155,000 addresses. 3 does not accept the s. It should start with 1.

**Comment by rohosalndn** [comment]
Ok thanks..
