### ISSUE TITLE
CPU priority support

### ISSUE THREAD

**Issue by adminnu** [brichard19/BitCrack#19]
Good afternoon!

I wanted first of all to express my gratitude that I realized a quick initialization! Thank you!

The task of the other, if I run several GPUs before the CPU load is 100%, I have in 2-5 hours, the server ceases to just answer, I have to restart. So, I put the same number of GPUs for CPU processes lower than normal and such failures were not observed. It would be nice to add a parameter that lowers the CPU priority, well, or downgrade it, unless of course this will not affect the performance.

**Comment by adminnu** [comment]
Did not start a separate bug, maybe this applies to the same problem. Sometimes the work of the application is frozen, for example I launched 2 video cards, I go on the trail. day into the system, and processes hang and do nothing, time in each window costs 2 hours, although much more time has passed. I press enter in each window, the process unfreezes and works further. I do not know if this is related to lowering the priority to cpu for processes, but here's the error.

**Comment by brichard19** [comment]
Hi there,

The CPU usage is fixed in the  latest build (0.16). The CPU usage should be near zero while the kernel is running.

Thanks

**Comment by adminnu** [comment]
Hi!

To be honest, I do not believe my eyes, first, when initializing cpu loaded 100% and then gradually began to decline, then the load slept and as if nothing worked at all, but he distorted the keys with the same speed!

I even checked if he finds addresses, checked on a pair of compressed ones, one to the beginning of the starting number, another far away, found both.

Thank you!
