### ISSUE TITLE
Own compilation very slow

### ISSUE THREAD

**Issue by MF1986** [brichard19/BitCrack#211]
Hi guys,

I hope someone can help me!

I'm using an RTX2070 it works fine with the build available in the release section (Cuda 9).

**Compilated with Cuda Toolkit 10.2:**
**Error List**: https://pastebin.com/jKghfeF7
**Output**: https://pastebin.com/e0najkA7

However, when I'm launching my own cuBitcrack.exe I only got 15 Mkey/s while with the same setup under Cuda 9 I can reach about 800 Mkey/s. There must be something that I forget or didn't setup correctly.

Compilation is under Visual Studio 2019 + Cuda Toolkit 10.2.

```
E:\>cuBitCrack.exe (settings)
[Info] Initializing GeForce RTX 2070
[Info] Generating 55,111,680 starting points (2102.3MB)
GeForce RTX 2070 6499 / 8192MB | 1 target 15.61 MKey/s
```

One more information, I can launch it without **cudart64_102.dll** into the folder while with cuda 9 it request the dll file. Am I missing something? Thanks in advance!

**Comment by MF1986** [comment]
Issue found! I was building in debug mode instead of release :)

**Comment by natedawg469** [comment]
> Hi guys,
> 
> I hope someone can help me!
> 
> I'm using an RTX2070 it works fine with the build available in the release section (Cuda 9).
> 
> **Compilated with Cuda Toolkit 10.2:**
> **Error List**: https://pastebin.com/jKghfeF7
> **Output**: https://pastebin.com/e0najkA7
> 
> However, when I'm launching my own cuBitcrack.exe I only got 15 Mkey/s while with the same setup under Cuda 9 I can reach about 800 Mkey/s. There must be something that I forget or didn't setup correctly.
> 
> Compilation is under Visual Studio 2019 + Cuda Toolkit 10.2.
> 
> ```
> E:\>cuBitCrack.exe (settings)
> [Info] Initializing GeForce RTX 2070
> [Info] Generating 55,111,680 starting points (2102.3MB)
> GeForce RTX 2070 6499 / 8192MB | 1 target 15.61 MKey/s
> ```
> 
> One more information, I can launch it without **cudart64_102.dll** into the folder while with cuda 9 it request the dll file. Am I missing something? Thanks in advance!

I was having the same issue and it was not fixed by putting it into release mode. Still have serious issues with mine.

**Comment by MF1986** [comment]
> I was having the same issue and it was not fixed by putting it into release mode. Still have serious issues with mine.

What kind of issues? 
I can share my version but there is nothing more than Cuda 10.2 at the moment.
Switching to release mode and clean + rebuild was the trick for me, I'm back to ~800 Mkey/s.
