### ISSUE TITLE
Does this look right? 

### ISSUE THREAD

**Issue by RB61** [brichard19/BitCrack#223]
on file CLKeySearchDevice.cpp

line 37 : _points = pointsPerThread * threads * blocks;

line 578: uint64_t totalPoints = (uint64_t)_points * _threads * _blocks;

does this look right?

**Comment by RB61** [comment]
Well
I changed line 578 from  : 
 uint64_t totalPoints = (uint64_t)_points * _threads * _blocks;
to:
 uint64_t totalPoints = (uint64_t)_points  ;

And things seem to work now :100:

**Comment by ghost** [comment]
Did the same. Really works fine now!!!

**Comment by kpot87** [comment]
> on file CLKeySearchDevice.cpp
> 
> line 37 : _points = pointsPerThread * threads * blocks;
> 
> line 578: uint64_t totalPoints = (uint64_t)_points * _threads * _blocks;
> 
> does this look right?

Hi ! Can you compile the file CL, and share on your repo? Thanks
