### ISSUE TITLE
'continue' in not work

### ISSUE THREAD

**Issue by alexgoroh** [brichard19/BitCrack#236]
Hello
How i use the "continue" option to save progress?
--continue progress.txt don`t create any file, but if i create 'progress.txt' - 
[2020-04-29.17:53:43] [Info] Loading ' progress.txt'
Z:\#CRYPT\BitCrack>pause

maybe i do something wrong ?
thnx.

**Comment by drgray** [comment]
same problem here

**Comment by drgray** [comment]
> Hello How i use the "continue" option to save progress? --continue progress.txt don`t create any file, but if i create 'progress.txt' - [2020-04-29.17:53:43] [Info] Loading ' progress.txt' Z:#CRYPT\BitCrack>pause
> 
> maybe i do something wrong ? thnx.
ok i just found what was wrong. if your starting for first time ofc there is nothing to load to program crashes.
if your just starting you should do example --continue D:\file.txt but you should not create that folder . just delete the file and let program make file for you

**Comment by alexgoroh** [comment]
Hi! cuBitCrack.exe -b 40 -t 256 -p 2730 --keyspace
FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF -o yes.txt -i in.txt --continue cont.txt
- is my string
the cont.txt file is create after 30sec, and renew every 30 sec
Just wait )

сб, 19 февр. 2022 г. в 21:09, drgray ***@***.***>:
