### ISSUE TITLE
Calculating Keyspace

### ISSUE THREAD

**Issue by rvrsh3ll** [brichard19/BitCrack#239]
Are there any tools or online websites for calculating keyspace given a specific private key?

**Comment by sqsezs** [comment]
www.privatekeys.pw use the private key search option

**Comment by rvrsh3ll** [comment]
If anyone else finds it handy, I created a script to calculate the time to cover a given keyspace with a specific mkey/s and share amount. 
https://gist.github.com/rvrsh3ll/c3ad6e200071be0e413a916db4f76c99

**Comment by Zerox456** [comment]
@rvrsh3ll
Tested but got errors:
`./Calculate-BitcoinKeySpaceBrute -startingexponent 40000000000000000 -endingexponent 7ffffffffffffffff -mkeys 60 -shares 1`
Errors:
./Calculate-BitcoinKeySpaceBrute: line 1: syntax error near unexpected token `('

./Calculate-BitcoinKeySpaceBrute: line 1: `Function Calculate-BitcoinKeySpaceBrute() {'

@sqsezs
I guess you mean [HERE](https://privatekeys.pw/key/00000000000000000000000000000000000000000000000000000e02b35a358f). Where exactly to look?
