### ISSUE TITLE
I built it successfully but .exe doesn't work

### ISSUE THREAD

**Issue by rezackg** [brichard19/BitCrack#241]
So I have been wanting to run bitcrack for a while now. I finally managed to build successful cuda build, I tried both 10.1 and 10.2, build is compiled successfully without errors. When I open program in debug it seems to work.

But when I try to open cuBitCrack.exe window just shows up and closes automatically in less than a second. I have no idea what is wrong. I am using window 10 64bit.

**Comment by MisterTeo** [comment]
Open CMD.exe and give a command there, and you will see what is the error, not using double click on cuBitCrack...

**Comment by rezackg** [comment]
cmd /K "C:\Users\Jovan\BitCrack-master\x64\Release\cuBitCrack.exe"

I managed to open it using this on cmd. How do I start actual program now to search for private keys? I would like to search for private keys with balances or whatever you guys are using here. I see commands but can't get start or whatever is supposed to run.

**Comment by MisterTeo** [comment]
I see you have no clue how to use windows OS and cmd.exe...
It's sad...
But, use search option in windows to find cmd. Open cmd console, and go to cuBitCrack.exe location and there use cuBitCrack.exe commands...
If you don't know how to do this, sorry, find tutorials, use youtube "how to start and use cmd.exe" and learn using windows first. After that, try to use BitCrack.

**Comment by rezackg** [comment]
I know how to do that and I have done that. I have opened .exe file in CMD and it is showing me all the commands. I just don't know which commands to use to run program and search for keys. I guess there is learning curve for all of us and I am sorry and I don't know everything, but I am willing to learn and ask for help.

**Comment by MisterTeo** [comment]
https://bitcointalk.org/index.php?topic=4453897.0
Read this topic. You will learn.

**Comment by rezackg** [comment]
Thanks man. I understood a lot of things. The only problem I am running into atm is that bitcrack won't open my input,output .txt file. They are in right folder where I am booting up cubitcrack.exe

cuBitCrack.exe -c -u -b 112 -p 512 -i walletadress.txt -o good.txt --keyspace  0000000000000000000000000000000000000000000000000000000000000001

I am using this and it says: Unable to open walletaddress.txt
For this I have found no solution. I would like to run software to search list of bitcoin addresses with balances, but it won't open them from .txt file. I assume that not everyone is just trying to break puzzle

**Comment by MisterTeo** [comment]
walletaddress.txt vs walletadress.txt . You see the difference ? :)
