### ISSUE TITLE
Building on VS2019 Cl version

### ISSUE THREAD

**Issue by Stefanzm** [brichard19/BitCrack#243]
Can someone give me precise pointers which files i have to change so to can build myself the clBitcrack version on windows ?
By default it complains about CL/cl.h not found at first sign .

I know where are the mistakes in the current code and will fix them (main.cpp , ClUnits and so on)  , but would want to know what else i have to fix .

**Comment by MisterTeo** [comment]
Install Open CL ( https://streamhpc.com/blog/2015-03-16/how-to-install-opencl-on-windows/ )

**Comment by Stefanzm** [comment]
Attempted it .. failed .. tired of trying . Will wait for a fixed version of the exe .

Thanks for the help
