### ISSUE TITLE
opencl kernel optimization

### ISSUE THREAD

**Issue by ghost** [brichard19/BitCrack#246]
I completely rewrote the secp256k1.cl code and got great results. 
But there is still a lot of work, there is still something to optimize.

**Before optimization it was like this**
![screen_old](https://user-images.githubusercontent.com/64967665/83260686-dfe0cb00-a1c2-11ea-9c2e-4e4b64afe1b1.png)

**After optimization**
![screen](https://user-images.githubusercontent.com/64967665/83260788-0acb1f00-a1c3-11ea-9072-aa380acce4b7.png)

**Comment by Uzlopak** [comment]
@AndrewBrz Can you provide the code please?
