### ISSUE TITLE
[question] How --continue works? 

### ISSUE THREAD

**Issue by maxya** [brichard19/BitCrack#251]
Sorry if this have been asked previously, but could you explain how doI continue after I've stopped and want to "continue" from last saved progress? 
So for example I've started work with : 
```sh
.\cuBitCrack.exe --continue run_one.dat -b 30 -t 512 -p 2096 -i btc_one.txt -o found_keys.txt -c --keyspace 0000000000000000000000000000000000000000000000001:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140
```

Do I **continue** with exactly the same command (would it overwrite existing continue file or will read from it ? : 
```sh
.\cuBitCrack.exe --continue run_one.dat -b 30 -t 512 -p 2096 -i btc_one.txt -o found_keys.txt -c --keyspace 0000000000000000000000000000000000000000000000001:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140
```

or I just run it like this : 

```
.\cuBitCrack.exe --continue run_one.dat
```

Thank you.

**Comment by MisterTeo** [comment]
It will continue from the last keyspace saved in .dat file...You can run it with both comands, and it will start from saved data...
