### ISSUE TITLE
How can i save the progress

### ISSUE THREAD

**Issue by balasid1404** [brichard19/BitCrack#273]
Please help me on step by step procedure to save the process and continue it later please...

**Comment by MisterTeo** [comment]
You can fund all your answers bere : https://bitcointalk.org/index.php?topic=4453897.0

**Comment by balasid1404** [comment]
Sir it is too long I cannot find the answer

**Comment by ghost** [comment]
add in arguments --continue continue.txt

**Comment by ghost** [comment]
BitCrack OPTIONS [TARGETS]
Where TARGETS is one or more addresses

-c, --compressed        Use compressed points
-u, --uncompressed      Use Uncompressed points
--compression  MODE     Specify compression where MODE is
                          compressed or uncompressed or both
-d, --device ID         Use device ID
-b, --blocks N          N blocks
-t, --threads N         N threads per block
-p, --points N          N points per thread
-i, --in FILE           Read addresses from FILE, one per line
-o, --out FILE          Write keys to FILE
-l, --list-devices      List available devices
--keyspace KEYSPACE     Specify the keyspace:
                          START:END
                          START:+COUNT
                          START
                          :END
                          :+COUNT
                        Where START, END, COUNT are in hex format
--stride N              Increment by N keys at a time
--share M/N             Divide the keyspace into N equal shares, process the Mth share
--continue FILE         Save/load progress from FILE

**Comment by balasid1404** [comment]
When will it save with it be saved after termination or while processing
itself?

**Comment by ghost** [comment]
Saving is done during processing in one minute interval.

**Comment by siupune** [comment]
use --continue -save1
