### ISSUE TITLE
Pay someone to help me set up on Vast.ai Linux

### ISSUE THREAD

**Issue by swatfa** [brichard19/BitCrack#281]
Want to run this on Vast.ai - i believe they use Ubuntu 16.01
RTX 3080 & RTX 3090 cards

If someone can prepare an easy way for me to load and run it then i can pay $90.

My usage case is as follows:
Usage 1: Load list of passwords from password.txt & list of addresses from addresses,txt and save any positive result to txt file
Usage 2: Generate random wallet addresses and compare to see if exists in addresess.txt file and if positive save to txt file

thanks

**Comment by bill32767** [comment]
Bitcrack should be used for educational purposes only. If you want to pay
someone, appreciate the creator @brichard19...
