### ISSUE TITLE
Any bitcrack experts here (need to know if this is possible)

### ISSUE THREAD

**Issue by swatfa** [brichard19/BitCrack#283]
Does anyone know if there's any possibility in bitcrack to work on multiple parts of the hex code at same time?

e.g.
starting hash
AAAAAAAAAAAAAAAAA

i want to break the process in bitcrack to the following:
Fixed                            S1                S2 
[AAA] [AAAAAA] [AAAAAAAA]

So default settings for Bitcrack is it will start counting from the last digit in 'S2' and continue incrementally. But what I want to do is to simultaneously work on S1 & S2 so that both are incrementally changing independently. Do you know if this is possible?

Thanks!

**Comment by ghost** [comment]
i dont know...
