### ISSUE TITLE
Can BitCrack be Used With NVIDIA A100 or other grid GPUs?

### ISSUE THREAD

**Issue by memiamp** [brichard19/BitCrack#294]
I was interested to know whether BitCrack can be run on a platform that supports the NVIDIA A100 GPU?

Obviously that will be running on a server not a desktop.

**Comment by bill32767** [comment]
Who supplies the server? Google cloud?

**Comment by memiamp** [comment]
> Who supplies the server? Google cloud?

What difference does that make?  Not that I see why it matters, but I have access to my own server.

**Comment by bill32767** [comment]
Some cloud servers do not support BitCrack.

**Comment by memiamp** [comment]
> Some cloud servers do not support BitCrack.

Great.  Do you know if BitCrack support the A100, which is the only thing I am trying to find out.

**Comment by bill32767** [comment]
I wouldn't know. You have to play around with it. To avoid head-like
errors, use Bitcrack0.21

**Comment by rdzar** [comment]
Would be awesome running that, but Ampere isn't supported afaik atm. There is a parallel issue in the CUDA code of Bitcrack, causing it to run into illegal memory. The A100 prob. would run into the same problem due to being Ampere arch.

**Comment by memiamp** [comment]
> Would be awesome running that, but Ampere isn't supported afaik atm. There is a parallel issue in the CUDA code of Bitcrack, causing it to run into illegal memory. The A100 prob. would run into the same problem due to being Ampere arch.

Thanks for clarifying.  I did suspect it would be the case that I couldn't use it.  It's a shame, as I'm sure it'd be impressive.
