### ISSUE TITLE
Max size of -i (read file)

### ISSUE THREAD

**Issue by ghost** [brichard19/BitCrack#309]
Been trying some -i read options and can say that 49k lines in a *.txt works good. But not 24 million lines... 
Whats the maximum addresses the clBitCrack and cuBitcrack versions can read?

**Comment by ghost** [comment]
Tried with 1 million addresses. Didn't work. Got 550K lines to work. Lost 50% of the speed though.

Searching now for 86 addresses within a certain range. Getting 135MKey/S. With 50 000 addresses speed was 115MKey/S. 550 000 addresses speed dropped down to 62MKey/S.

The files sorted in order A-Z. Maybe there is a better way to sort so the computer can read faster. It does look like the bottle neck is amount of addresses and not the actual calculations.

Using a Rysen 16 core, 64 GB ram and a GTX 1650. Will buy better GTX cards when available. All sold out now.

**Comment by SaxoBeatMos** [comment]
> Been trying some -i read options and can say that 49k lines in a *.txt works good. But not 24 million lines...
> Whats the maximum addresses the clBitCrack and cuBitcrack versions can read?

![Screenshot_4](https://user-images.githubusercontent.com/13357161/108585363-7ef8b480-7348-11eb-936c-3e7d8046d27d.png)
![Screenshot_5](https://user-images.githubusercontent.com/13357161/108585399-a780ae80-7348-11eb-9aae-63bef2566fbc.png)

24 million rows normally loads
only long 3 minutes

**Comment by RastaDollo** [comment]
Maybe, Need minimum start points

**Comment by ghost** [comment]
Not sure I follow this as my Russian skills are not good at all. Only know left/right and halt... 
There must be some settings I have wrong.

**Comment by SaxoBeatMos** [comment]
> Not sure I follow this as my Russian skills are not good at all. Only know left/right and halt...
> There must be some settings I have wrong.

look through the file for extra spaces, it may cause loading errors.

**Comment by SaxoBeatMos** [comment]
download the address dump
https://balances.crypto-nerdz.org/balances/balances-bitcoin-20210220-0100-6GbSjOZU.gz
remove the extra addresses from there and try to give the program

I can give you the processed file

**Comment by ghost** [comment]
Was one empty line in the file. Removed it and now it works great. EmEditor is really excellent.
+24M keys loading in 1 min and 11 sec.

Thanks for the offer of processed file. Have one that is a few days old so will use it.

**Comment by sezginyildirim91** [comment]
> download the address dump
> https://balances.crypto-nerdz.org/balances/balances-bitcoin-20210220-0100-6GbSjOZU.gz
> remove the extra addresses from there and try to give the program
> 
> I can give you the processed file

First of all thank you for the file. Are addresses starting with 3 and bc unnecessary? Do I need to remove them?

**Comment by SaxoBeatMos** [comment]
> > download the address dump
> > https://balances.crypto-nerdz.org/balances/balances-bitcoin-20210220-0100-6GbSjOZU.gz
> > remove the extra addresses from there and try to give the program
> > I can give you the processed file
> 
> First of all thank you for the file. Are addresses starting with 3 and bc unnecessary? Do I need to remove them?

Addresses starting with 3 and bc are not needed, they need to be deleted.
