### ISSUE TITLE
Does it require an attention?

### ISSUE THREAD

**Issue by mrantonion** [brichard19/BitCrack#323]
Look.
I defined a range to search (64th puzzle) from AAACED1A00000000 to AAACED3300000000 stepping 1. If we substract the 2nd number from the 1st we will get 107 374 182 400. So why we see at the screenshot, that the cuBitCrack passed only 105 696 460 800 numbers? And that's not the first case. Very often 1 see 107Millions, sometimes i see 105Millions. Why this occurs?
![cuBitCrack_001](https://user-images.githubusercontent.com/78864485/114304334-3903d580-9adb-11eb-9940-52493c2beae0.PNG)

Can i consider this situation as incorrect calculations or it is not worth of attention?

**Comment by ghost** [comment]
By default this field is updated every 2 seconds. So if you reach end of keyspace the last update is not shown.

**Comment by mrantonion** [comment]
> By default this field is updated every 2 seconds. So if you reach end of keyspace the last update is not shown.

Thank you very for your answer!
Sorry for a long reply. :)

**Comment by websonder** [comment]
@mrantonion have you  completely scan  this series AAACED1A00000000 to AAACED3300000000 ?

**Comment by mrantonion** [comment]
> @mrantonion have you completely scan this series AAACED1A00000000 to AAACED3300000000 ?

I did.
