### ISSUE TITLE
🚀  Programs for finding bitcoin here 🚀 

### ISSUE THREAD

**Issue by ghost** [brichard19/BitCrack#339]
Hi bitcoin hunters!
The BitCrack project is abandoned and is not being updated.
I invite you to familiarize yourself with fast programs: 

Telegram group [**BTC Hunters**](https://t.me/wif500)

[**Rotor-Cuda**](https://github.com/phrutis/Rotor-Cuda) 
[**WifSolverCuda**](https://github.com/phrutis/WifSolverCuda)
[**Fialka M-125**](https://github.com/phrutis/Fialka)
[**GPU Cillider**](https://github.com/phrutis/Collider)

And others [repisitories](https://github.com/phrutis?tab=repositories)

Have a good hunting!

**Comment by secp8x32** [comment]
Appreciable work but you should share the source codes for the changes that you made, it'll help someone else to add new features to them.

**Comment by phrutis** [comment]
Today I will add the modified sources of Rotor-Cuda, Rotor-Speed. What to do with the Rotor project, which is on OpenCL, I do not know. It weighs ~900mb a lot of files. There are .lib files more than 50mb github does not allow them to download. Many #include files and libraries can be rewritten manually for yourself and it's not a fact that they will be assembled on another PC. When compiling, Visual Studio torments me with errors, and I have questions like help error C2065. I'll try to think of something. If the masters need the original sources, they can find them from [you](https://github.com/kanhavishva?tab=repositories)

**Comment by ilkerccom** [comment]
This is optional and very simple solution. But very low speed on CPU and C#

[ilkerccom/bitcoinpuzzlescanner](https://github.com/ilkerccom/bitcoinpuzzlescanner)
