### ISSUE TITLE
Released and custom builded is different

### ISSUE THREAD

**Issue by ilkerccom** [brichard19/BitCrack#349]
When I tested the Released version I was scanning 300 million per second.

When I build the code myself, the speed shows 5 million per second. Which one is correct?

I have a 2080 Ti graphics card.

![test](https://user-images.githubusercontent.com/35669865/151172309-ba4f2204-2806-4cd6-a28d-e39f63a19b2b.png)

**Comment by sezginyildirim91** [comment]
Your own compilation is wrong, it's normal to have 300 million with your video card. You can increase the speed even more with the -b -p -t parameters. By the way, I'm in TR, we can share our ideas together on telegram. @sezginyil

**Comment by MisterTeo** [comment]
Try to compile it in Visual Studio as RELEASE, not DEBUG !
