### ISSUE TITLE
Tesla P100 , Error: invalid device symbol Exiting

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#40]
here some need help
./cudainfo
Found 1 devices

ID: 0
Name: Tesla P100-PCIE-16GB
Capability: 6.0
MP: 56
Cores: 3584 (64 per MP)
Memory: 16280MB
ERROR after run Bitcrack

./BitCrack -u 1Pzxbxz9Lfcgd3cJZ4XsEraARE1FhVbCCe
[2018-09-20.06:59:59] [Info] Compression: uncompressed
[2018-09-20.06:59:59] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-09-20.06:59:59] [Info] Initializing Tesla P100-PCIE-16GB
[2018-09-20.06:59:59] [Info] Generating 7,340,032 starting points (280.0MB)
[2018-09-20.07:00:00] [Info] Error: invalid device symbol Exiting.

2nd ERROR

./BitCrack -b 32 -t 256 -p 16 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
[2018-09-20.07:02:49] [Info] Compression: compressed
[2018-09-20.07:02:49] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-09-20.07:02:49] [Info] Initializing Tesla P100-PCIE-16GB
[2018-09-20.07:02:49] [Info] Generating 131,072 starting points (5.0MB)
[2018-09-20.07:02:49] [Info] Error: invalid device symbol Exiting.

machine is linux strech 9 , pytorch, cuda toolkit 9.2 installed
GPU info on top

ANY Guideline where is problem ?

**Comment by hamnaz** [comment]
thankx its working now,
will post more results and issues if any

**Comment by jamesyoungdigital** [comment]
I did "make BUILD_CUDA=1 COMPUTE_CAP=60".

Same issue, with Tesla V100. Ubuntu 16.04LTS, CUDA 9.2:

james@research:~/BitCrack/bin$ ./cuBitCrack -d 0 ~/unspentbtc.txt -o ~/cracked.txt &
[1] 22686
james@research:~/BitCrack/bin$ [2018-11-18.11:06:03] [Info] Compression: compressed
[2018-11-18.11:06:03] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-11-18.11:06:03] [Info] Initializing 
[2018-11-18.11:06:03] [Info] Generating 262,144 starting points (10.0MB)
[2018-11-18.11:06:03] [Info] Error: invalid device symbol Exiting.

Any ideas?

**Comment by jamesyoungdigital** [comment]
Found it: http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

COMPUTE_CAP=70

All good

**Comment by jamesyoungdigital** [comment]
LOL!  ;=)

I got there quicker because I just had to try it out!  Genius work mate, it's fantastic.  Much easier to work with than my sets of 96-CPU instances, controlling them with crappy home made scripts etc. Haha.

I did get to 122AJhKLEfkFBaGAd84pLp1kfE7xK3GdT8 and found the private key in less than 48 hours though, not bad for CPU work.

I'm looking for your BTC address, I'm sure it's here somewhere.  I'll send on some tips! 👍

**Comment by brichard19** [comment]
> I'm looking for your BTC address, I'm sure it's here somewhere. I'll send on some tips! 

It's at the bottom of the main project page:

https://github.com/brichard19/BitCrack


What kind of speed were you getting on CPUs? And what kind of CPUs were they? I'm thinking of doing a CPU implementation.

**Comment by jamesyoungdigital** [comment]
Xeon CPUs, not the best, but alright.  I was getting at least 33.6 million keys/sec on a 96-CPU machine.

It works out very well for me when I can tell the processes in groups to work on different keyspaces, starting from certain points.  I had to do that to crack quickly.  I'm still experimenting to get better results.  It's not bad, and if you're renting, it's cheaper than GPUs that's for sure!

Some hand-written assembler wouldn't go astray, even though the speed up might not be terrific compared to tight C/C++ code.

**Comment by jamesyoungdigital** [comment]
What I really want to do is an implementation with highly optimised CPU code for an AMD Threadripper 64-core machine.

Just need the money for the machine now... will get there sooner or later.  About mid way through next year I should have it and some decent code to start test cases with.

**Comment by brichard19** [comment]
> Xeon CPUs, not the best, but alright. I was getting at least 33.6 million keys/sec on a 96-CPU machine

I thought it would be at least 1 million keys/sec per core. Interesting.

**Comment by jamesyoungdigital** [comment]
> > I was getting at least 33.6 million keys/sec on a 96-CPU machine.
> > it's cheaper than GPUs that's for sure!
> 
> Weird things you write... U'll get approximately 10 times higher speed on quite pathetic gtx1070

Yes, I didn't have GPUs at that point, so it was CPUs.  I had them set up for other research projects, so I thought I'd try and understand how it works then try GPUs.

**Comment by jamesyoungdigital** [comment]
> > Xeon CPUs, not the best, but alright. I was getting at least 33.6 million keys/sec on a 96-CPU machine
> 
> I thought it would be at least 1 million keys/sec per core. Interesting.

I can get 500,000 per core, thereabouts.  The cores are not that great.  If you go to AWS and get big compute instances, then yes you'll get millions per core.

**Comment by jamesyoungdigital** [comment]
I want to see what I can get with an AMD Ryzen Threadripper 64-core.  That's going to be a project of mine; I will fork later and help work on CPU cracking if that sounds alright with you.

**Comment by bill32767** [comment]
Can I run both CPU and GPU bitcrack on same computer? When I try to run
clbitcrack it uses GPU instead of CPU, please advise and how can I see my
CPU properties to be sure it has compatible OpenCL? Thanks.
