### ISSUE TITLE
The bitcrack chagrin

### ISSUE THREAD

**Issue by turalyf** [brichard19/BitCrack#421]
Hello friends.

Bit crack without randomness is a useless utility.

Because, for example, to generate a bitcoin **puzzle 69** search, it will take exactly **_34188 days_** — that's **93** years at a speed of **_200 MH_** keys per second to reach the last range of **590295810358705651712**.

**Comment by lostuser719** [comment]
Before giving advices, you should do your math properly again :) 
200 MH keys per second is 200 milions (200 000 000) MH keys per second

Your calculation would be correct, if a machine would do 200 billions (200 000 000 000) keys per second.

Therefore, the machine doing 200 MH keys per second, that you mentioned, would search the range in 93 000 years.

Anyway, I do not think that adding the randomness would improve your chances. If you have some proof, feel free to add it.

Cheers!

**Comment by turalyf** [comment]
Good afternoon, dear.
I did the math wrong, so i closed the topic.

Thank you for bringing up the issue, i didn't want to lead anyone astray.

In any case, even if the speed is 1Pkeys or more, "randomness" still wins.

**Comment by lostuser719** [comment]
Hi, 
thank you for making it clear, I apprecatiate that you admitted your mistake :)
About the randomness, could you please explain a little bit more, why does it find the solution faster? Do you mean, that every key that is compared, should be random one? I want to learn more about this topic, so I am open about your solution.
Thank you

**Comment by turalyf** [comment]
I would love to explain it to you :) But unfortunately I am writing to you with a Google translator :) On the score of chance, I would say this, which is related to codes, utilities with hacking bitcoin in Github, 90 percent have been tested by me :) I'm mainly interested in " random" puzzles with up to 160 bits, it's perfect. And here the speed of generation decides, for the test with 30-45 puzzles, my first search for each puzzle took differently, 5, 8, 19, 25, 32, 38, 45 min. etc. hour and no more, this is taking into account the speed of 650-690 megakeys per second.

maybe I am mistaken in my opinions and reports, but hope dies last. We keep looking, we don't stop.. 

I will test another project at the moment, if everything goes well, I will share it with you. 

Have a nice day.
