### ISSUE TITLE
Brainwallet function

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#47]
before a month peoples look a bainwallet function , load there wordlist > hash256 > (verify address )
brainflayer already exist for this but not for GPU based testing, 
in short every one looking brainwallet function in BitCrack as its fast checking on GPU
Hope you take an action about this function
any programmer can explain here about this subject more
thankx

**Comment by prodnet** [comment]
Nobody responds to our questions?
brichard19, please let me know.
Thanks.

**Comment by natedawg469** [comment]
Its already been discussed in another issue discussion

**Comment by hamnaz** [comment]
another issue open  with same questions, but not tag about ..., nor discuss, only there are question
waiting reply from developer,
ther is lot of issue pending, like
Brain wallet function
seed function
random hex function
and more ... :)

**Comment by brichard19** [comment]
> Brain wallet function
> seed function
> random hex function

None of these are in the pipeline right now. I don't think the random key generation has merit - the probability of finding any private key through random guessing is too low to be practical.

**Comment by andreyyv** [comment]
Hi! Can you add function that can generate passphrase like crunch?

**Comment by prodnet** [comment]
I see that Brainflayer's functionalities have not been implemented by "brichard19"...
Is it really so difficult to implement brainwallet dictionary attack (SHA256 (passphrase))  to run on GPUs?

**Comment by brichard19** [comment]
It's not difficult. It takes time and resources and this is less than a part-time project for me.
