### ISSUE TITLE
Increment chnages

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#48]
i am looking increment changes as per switch, by default its uses +1
example
BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000000 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
next is BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000001 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
what i am looking user assign switch for increment add 
example 
BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000000 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
then +500 increment
BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000501 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH

next +500 increment add into hex, not in digit

any solution

**Comment by brichard19** [comment]
#68 will address this
