### ISSUE TITLE
BitCrack-master\x64\Release\secp256k1lib.lib is not a valid Win32 application ???

### ISSUE THREAD

**Issue by voyagerlife** [brichard19/BitCrack#49]

**Comment by brichard19** [comment]
`KeyFinder` project is what builds BitCrack64.exe. Sounds like you're trying to build and run secp256k1lib.

**Comment by voyagerlife** [comment]
How should I install the program as release then?

**Comment by voyagerlife** [comment]
After downloading and extracting files, the only file to choose and open it on visual studio is "BitCrack.sln"
And when I open it and start building the project as release, I'm getting errors... What am I doing wrong?

**Comment by nightwalker89** [comment]
I get the same error first time.
Just select KeyFinder as the start project in solution properties

**Comment by brichard19** [comment]
> I get the same error first time.
Just select KeyFinder as the start project in solution properties

It should have already been the default project. Interesting.

**Comment by Toroop78** [comment]
> `KeyFinder`проект - это то, что создает BitCrack64.exe. Похоже, вы пытаетесь построить и запустить secp256k1lib.

this issue has already been discussed
https://github.com/brichard19/BitCrack/issues/25#issuecomment-417522027

**Comment by voyagerlife** [comment]
This edit #if _MSC_VER < 1600 || _MSC_VER > 1915 and starting the project from KeyFinder solved it.

But when I drop and drag the BitCrack64 which is in x64>Release to cmd, I get the following error.

 **[Error] Error detecting CUDA devices: CUDA driver version is insufficient for CUDA runtime version**

I tried it either with x86 Cmd or x64 Cmd but same error..

Any idea?

**Comment by nightwalker89** [comment]
Uninstall all Nvidia drivers. 
Install Cuda toolkit, select Nvidia Driver also. That is how I fix this issue.

**Comment by voyagerlife** [comment]
No success, same error...

**Comment by voyagerlife** [comment]
@brichard19 @Toroop78 @nightwalker89 Below is the download link of latest version of CUDA 9.2 Toolkit 9.2.148 and a patch 9.2.148.1 link.

https://developer.nvidia.com/cuda-92-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal

Do I need to install a lower version? 

It would be great if the program would work with an up to date latest cuda version, that we don't spend many hours and days to get it working...

**Comment by voyagerlife** [comment]
Nvidia 8600m gt but it gives exactly the same error on another laptop with intel hd graphics. I don't think that it's a graphic card issue. Another user recommends me to downgrade cuda to 9.2.88
I haven't downgrade the cuda yet, but I don't think that it'll solve it. I'll let you know after I give a try..

**Comment by brichard19** [comment]
> Nvidia 8600m gt

I'm sorry to tell you that this device is too old. CUDA 9.2 does not support devices with compute capability < 3.0 (Tesla, Fermi).

**Comment by voyagerlife** [comment]
Should it be only Nvidia, or Intel Hd Graphic is fine too?

**Comment by brichard19** [comment]
CUDA only runs on Nvidia hardware.

I am working on an OpenCL implementation which will work on more devices. I'm not sure if your Intel graphics has OpenCL support.

**Comment by voyagerlife** [comment]
Yes, it has. Here is the screenshot.

![opencl](https://user-images.githubusercontent.com/12533512/46556711-c1400900-c8e7-11e8-91a8-832f9f56a060.PNG)

**Comment by voyagerlife** [comment]
When can I try OpenCL version?

**Comment by successhalf** [comment]
help me set the command line with the instructions below

BitCrack.exe [OPTIONS] [TARGETS]

Where [TARGETS] are one or more Bitcoin address

Options:

-i, --in FILE
Read addresses from FILE, one address per line. If FILE is "-" then stdin is read.

-o, --out FILE
Append private keys to FILE, one per line.

Bitcrack.exe ......?

**Comment by successhalf** [comment]
help me cudart64_92.dll error

**Comment by voyagerlife** [comment]
> When can I try OpenCL version?

@brichard19 I unfortunately didn't hear from you? 
Out of that, will it also be possible to use the program with AMD graphichs card?

**Comment by voyagerlife** [comment]
@brichard19 do you have any news about OpenCL implementation?

**Comment by wrcdcom** [comment]
```
---------------------------
BitCrack.exe - System Error
---------------------------
The code could not be continued because the system did not detect the cudart32_80.dll. To resolve this issue, try reinstalling the program.
---------------------------
```
As I understand it, the error was related to the video card. I updated my nvideo

 
I have Windows 10 / 32bit / I use NVIDEO GeForce GT 650M

The error did not disappear !!

Something very much confused! How to fix it?
Be kindly help please with the launch!

**Comment by voyagerlife** [comment]
@wrcdcom I unfortunately have no clue, I built a new PC and don't get this error. You should read the comments about setting up the programm and follow the steps.

**Comment by crypto-artisan** [comment]
![Screenshot_2024-08-19_154931](https://github.com/user-attachments/assets/54e0ed1d-57a4-4f2b-959d-a7d14bcc2e9d)
Hey, @wrcdcom
I faced same error.
Was you able to resolve this problem?
Id like to hear from you

Here is my conf info:
-MS Visual Studio 2019
-Nvidia Geforce GT 730
-Nvidia Toolkit SDK 10.1

Who guy can help me?
Thanks in advance
