### ISSUE TITLE
Error detecting CUDA devices: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by voyagerlife** [brichard19/BitCrack#50]
Did anybody get this error when you drag and drop the built BitCrack64 to CMD ???

I uninstalled and reinstalled Cuda 9.2 many times, but it's not a solution. The Cuda version is 9.2.148.1

**Comment by Simkas45** [comment]
installing cuda_9.2.88_win10.exe.
I helped install this version

**Comment by voyagerlife** [comment]
@Simkas45 Did you have the same error?

**Comment by Simkas45** [comment]
yes

**Comment by Simkas45** [comment]
i uninstalled all nvidia programms reboot, and install installing cuda_9.2.88_win10.exe.

**Comment by voyagerlife** [comment]
Ok. Thanks, I'll give a try and let you know

**Comment by Simkas45** [comment]
okay

**Comment by voyagerlife** [comment]
cuda_9.2.88_win10.exe doesn't solve the issue either, it's not a toolkit issue.

**Comment by Toroop78** [comment]
> Кто-нибудь получил эту ошибку при перетаскивании встроенного BitCrack64 в CMD ???
> 
> Я удалил и повторно установил Cuda 9.2 много раз, но это не решение. Версия Cuda - 9.2.148.1

what parameters do you run BitCrack64?

**Comment by voyagerlife** [comment]
I mean BitCrack64 in Release folder doesn't even start in Cmd. Neither on x86 nor on x64 Cmd.

**Comment by Toroop78** [comment]
> Я имею в виду, что BitCrack64 в папке Release даже не запускается в Cmd. Ни на x86, ни на x64 Cmd.

https://github.com/brichard19/BitCrack/issues/49#issuecomment-427208878

**Comment by successhalf** [comment]
help me set the command line with the instructions below

BitCrack.exe [OPTIONS] [TARGETS]

Where [TARGETS] are one or more Bitcoin address

Options:

-i, --in FILE
Read addresses from FILE, one address per line. If FILE is "-" then stdin is read.

-o, --out FILE
Append private keys to FILE, one per line.

Bitcrack.exe ......?
