### ISSUE TITLE
Is it possible to increase productivity?

### ISSUE THREAD

**Issue by PsyShark** [brichard19/BitCrack#53]
As far as I understand, at the moment, the BitCrack program converts the private key to the full address and compares it with the list of addresses. This action consists of 9-10 steps.
Is it possible in this program to increase productivity by reducing the number of steps to 3 or 4 using the following scheme:
1. Using a separate utility, convert the address list to RIPEMD-160 from the file addr.txt to the file out.txt
2. When starting BitCrack instead of the address list, use the RIPEMD-160 list.
3. The BitCrack program takes the specified key, converts it to RIPEMD-160 and compares it with the list obtained in paragraph 1 of this scheme.

**Comment by brichard19** [comment]
Hi, 

BitCrack already does this. The addresses are converted to their RIPEMD160 hashes and inserted into a list (for a small number of addresses) or bloom filter (for a large number of addresses) in the GPU memory.

**Comment by PsyShark** [comment]
Thanks for the answer.

Please tell me where you can read on the algorithm for converting the key in the RIPEMD-160?

**Comment by PsyShark** [comment]
In programming, I am weak. I meant an article with a detailed description of the conversion to RIPEMD-160 (you suddenly came across).

There is an idea regarding the numerical distance between the addresses. For example, there is a key 000000000000000000000000000000000000000000000000000000000001 to the address 1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH and RIPEMD-160 = 751E76E8199196D454941C45D1B3A333333333333333403.
But if in the RIPEMD-160 to change the last character by 1 unit more (751E76E8199196D454941C45D1B3A323F1433BD7), we get the address 1BgGZ9tcN4rm9KBzDn7KprQz87SZCaYa6H. The changes are insignificant, but there is an interest to find out how much the distance in the keys between these addresses, that is, starting from the 1st key and how many keys the second address will appear.
Is it possible to implement in your program (or a separate tool) search by prefix (with an incomplete address)?

**Comment by brichard19** [comment]
This is the article I read:

[https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses)

**Comment by PsyShark** [comment]
Thanks

**Comment by PsyShark** [comment]
Fantasy played out, you can take a note (suddenly like it).
Regarding the generation of random keys in a limited range of keys.
Example: The beginning of the range 00000000000000000000000000000000000000000000000100000000000000
End of the range 00000000000000000000000000000000000000000000000200000000000000
A random key is generated in the specified range, a specified number of keys are checked against a random key (say 100,000,000,000), at the end of the scan a new random key is generated, and 100,000,000,000 keys are checked again.
It would also make sense to write to the file the scanned ranges in the form of the initial key - the final key. And when generating a new point of reference, the program checks the scanned ranges, if the generated key falls within the already passed range, then it takes the next key from the scanned range as a reference point and continues to check the specified number of addresses.
Example: Started with the key 0000000000000000000000000000000000000000000010000000000000000
        scanned the keys 100,000,000,000
        finished the scan 0000000000000000000000000000000000000000000000010000174876E7FF
        generate a random key in the range from 100000000000000 to 200000000000000
        if you are in the already scanned range from 100000000000000 to 10000174876E7FF
        then we begin to scan the next 100,000,000,000 keys from the key 10000174876E800
        if there is no match with the record, then scan 100,000,000,000 from a randomly generated key 745E91AA0079BB5.
To reduce the space occupied by the file of the passed keys, take notes in the form:
the beginning of 1000000000000
end 10000174876E7FF
the beginning 745E91AA0079BB5
end of 745E931E87E83B4
if you fall into the range covered, then only the final key
the beginning of 1000000000000
end of 10000174876E7FF this entry is overwritten
end 100002E90EDCFFF this entry is written
and we get 2 lines: the beginning of 100000000000000
end of 100002E90EDCFFF

**Comment by successhalf** [comment]
> Fantasy played out, you can take a note (suddenly like it).
> **Thanks for attention.**
give me your email or skype

**Comment by PsyShark** [comment]
For what purpose? I am not a programmer.

**Comment by successhalf** [comment]
> For what purpose? I am not a programmer.

OK
thank you
