### ISSUE TITLE
Test finding one private key

### ISSUE THREAD

**Issue by Dragoula** [brichard19/BitCrack#54]
Hello! Thank you for the software!

I would like to know how can I test (simulate) finding one private key.
For example, I know both the private key:"12345F..." and the respective BTC address:"ABC1...". 
Can I find the private key by searching for the key of that address:"ABC1..." starting the search on "12345F..." privkey ?

**Comment by PsyShark** [comment]
you can check what is the speed in the keys on your video card and what kind of card

**Comment by Dragoula** [comment]
Hi! I meant actually find one priv key to see what the program does.
I used a known public address and its respective privkey. 
The program instantly finds the privkey (as expected).

But in my case **right after it finds the privkey it closes the window**. Not giving me time to copy it.

What can I do to not let the window close?

**Comment by PsyShark** [comment]
First open cmd, then write a command in the command line, in this case the window will not close. Use the -o out.txt option.
When finding the key, the program will write the result to the file out.txt

**Comment by Dragoula** [comment]
Thank you!!
The window doesn't close when running it from the cmd. 👍 
I just can't get the out.txt in the end. Do you have any idea what it might be?

**Comment by PsyShark** [comment]
the out.txt file must be created in the bitcrack folder

**Comment by Dragoula** [comment]
But is it previously created manually be me? or the software generates it?

**Comment by Dragoula** [comment]
This is what I get when program finishes, successfully finding a priv key for my target:
<img width="663" alt="capture" src="https://user-images.githubusercontent.com/38354878/46875726-656c0780-ce34-11e8-9c99-4cea24020c30.PNG">

but the out.txt file is not created.

**Comment by PsyShark** [comment]
try moving the **-o out.txt** parameter between **-u** and **-s** parameters

**Comment by Dragoula** [comment]
![capturar](https://user-images.githubusercontent.com/38354878/46877975-f72a4380-ce39-11e8-98a2-d20c55dd082d.JPG)

It assumes target as "-o"

About the keys/second:
With -b 32 -t 256 -p 16 I get -> 85 Mkeys/sec
With -b 32 -t 256 -p 32 I get -> 95 Mkeys/sec

**Comment by PsyShark** [comment]
what version of bitcrack?
here is a new release
https://github.com/brichard19/BitCrack/releases/tag/0.21
This file **cudart64_92.dll** is also needed, download CUDA 9.2, unpack (no need to install) and copy to the folder with bitcrack.

**Comment by Dragoula** [comment]
Sorry for making you lose time, I was using an old release 0.0.6 ...
Downloading CUDA 9.2 to get the cudart64_92.dll, is there any other file needed?

Thank you for everything

**Comment by PsyShark** [comment]
Unfortunately, *.dll anywhere except CUDA 9.2 did not find (it was necessary to swing). In the project it is not likely because of the license.

**Comment by Dragoula** [comment]
Thank you for everything. Things are running well now.

How much speed do you get with your card?

**Comment by PsyShark** [comment]
with one compressed key 249MKey/s
uncompressed about 200Mkey/s
1070

**Comment by Dragoula** [comment]
What parameters are you using?

**Comment by PsyShark** [comment]
-b 30 -t 256(512) -p 512(1024)
