### ISSUE TITLE
"Kernel error Caught CUDAexception" What's the reason for this error?  

### ISSUE THREAD

**Issue by Dragoula** [brichard19/BitCrack#55]
![capturar](https://user-images.githubusercontent.com/38354878/47075024-87c6a200-d1f3-11e8-8761-3d0caddedce5.JPG)

Happened for the first time last night.

Thank you

**Comment by brichard19** [comment]
Good to see people are seriously running this.


Hmm. Are you running on Windows? Is this device also driving a display?

**Comment by Dragoula** [comment]
Yes, but it is turned off. I access it remotely.
