### ISSUE TITLE
How to know if a Bitcoin address is compressed or uncompressed?

### ISSUE THREAD

**Issue by Dragoula** [brichard19/BitCrack#56]
There is no way to know, unless you have the private key, right?

In which cases should I use  -c (for compressed) or -u (for uncompressed) ?

**Comment by brichard19** [comment]
Compression is performed on the public key.

Most Bitcoin addresses since I think 2013 are compressed. The puzzle transaction addresses are compressed.


If you are really unsure you can use -c -u and it will compute both, but there is a performance penalty.

**Comment by Dragoula** [comment]
Got it! Thank you for the clarification!

**Comment by bill32767** [comment]
Use both  -c  -u if you are not sure. The public key of a compressed
address starts with 01 or 02. The public key of an uncompressed address
starts with 04.

**Comment by Dragoula** [comment]
I'm using both 👍 
Since the search of the private keys are in order and not random, where can I look for intervals of search? The search is in hexadecimal, so I have a bit of difficulty visualizing the possible intervals, can you help me somehow?

**Comment by brichard19** [comment]
Hi,

I'm not sure I understand your question. Can you elaborate?

Keyspaces are typically specified in bits, so hexadecimal is a natural format to represent keys.

**Comment by PsyShark** [comment]
2^0=1
2^1=2
2^2=4
2^3=8
2^4=16
2^5=32
2^6=64
2^7=128
2^8=256
2^9=512
2^10=1024
...
2^256=115792089237316195423570985008687907853269984665640564039457584007913129639936
The last valid key is slightly less than 2^256. It is equal to 115792089237316195423570985008687907852837564279074904382605163141518161494336
