### ISSUE TITLE
Error running clBitCrack

### ISSUE THREAD

**Issue by PsyShark** [brichard19/BitCrack#63]
```
[2018-10-31.11:13:28] [Info] Compiling 'KeySearch.cl'...
[2018-10-31.11:13:28] [Info] Error: C:\Users\Admin\AppData\Local\Temp\\OCL4956T3.cl:1:10: fatal error: 'sha256.cl' file not found
                             #include "sha256.cl"
                                      ^
                             1 error generated.

                             error: Clang front-end compilation failed!
                             Frontend phase failed compilation.
                             Error: Compiling CL to IR
```
Folder contents
```
D:\Mining\BitCrack 0.22

31.10.2018  10:38    <DIR>          .
31.10.2018  10:38    <DIR>          ..
31.10.2018  08:32            68 096 AddrGen.exe
22.09.2018  01:52            13 007 Bitcrack.png
22.09.2018  02:27               855 BitCrack.txt
31.10.2018  08:35               143 btc.bat
23.10.2018  22:56       233 958 434 btc.txt
31.10.2018  08:32           151 552 clBitCrack.exe
31.10.2018  08:32         2 311 680 cuBitCrack.exe
31.10.2018  08:32            17 920 cudaInfo.exe
13.06.2018  07:53           368 128 cudart64_92.dll
11.10.2018  22:54               764 FAQ.txt
31.10.2018  08:33            10 964 keysearch.cl
15.06.2015  15:32           634 528 msvcp140.dll
31.10.2018  08:33            16 216 ripemd160.cl
31.10.2018  08:33            13 926 secp256k1.cl
31.10.2018  08:33            20 816 sha256.cl
23.06.2015  15:00            88 248 vcruntime140.dll
              16 files    237 675 277 byte
               2 folder  61 911 756 800 byte
```

**Comment by brichard19** [comment]
I see. Looks like it is copying it to another directory and then compiling. This doesn't happen on my system with an nVidia card.

As a work-around you could try replacing the #include statements inside keyfinder.cl with the contents of those files.

I will release an update with a merged .cl file.

**Comment by PsyShark** [comment]
Question regarding the version for nvidia, were there any changes in the program code with the transition from v.0.21 to v.0.22?
The question arose due to the difference in keys processed per second:
with the same parameters in v.0.21, the average is 249 MKey / s (1 compressed address), and in v.0.22 it turns out 240 MKey / s (1 compressed address).

**Comment by bill32767** [comment]
Works fine for me. I'm running it on  a nVidia card computer....

**Comment by PsyShark** [comment]
> Works fine for me. I'm running it on a nVidia card computer....<

Both versions (0.21 and 0.22) work well on nvidia, but the last one is slightly inferior in terms of the number of keys per second.

**Comment by prodnet** [comment]
Run in multi AMD GPUs cards?
What driver do you preconise for linux?
I have Ubuntu 18.04 with Mesa and ROCm  drivers installed.

I have this error message:

`CL user error: clEnqueueFillBuffer() requires OpenCL version 1.2 or greater.
terminate called after throwing an instance of 'cl::CLException'
Abandon (core dumped)`

**Comment by dem10** [comment]
The same mistake as PsyShark .
[2018-11-01.14:08:56] [Info] Compiling 'KeySearch.cl'...
[2018-11-01.14:08:56] [Info] Error: C:\Users\Vel\AppData\Local\Temp\\OCL8792T5.cl:1:10: fatal error: 'sha256.cl' file not found
                             #include "sha256.cl"
                                      ^

                             error: Clang front-end compilation failed!
                             Frontend phase failed compilation.
                             Error: Compiling CL to IR

**Comment by dem10** [comment]
The all cl files should be placed in the folder Temp,clBitCrack.exe reads and compiles them in this folder.

**Comment by dem10** [comment]
> ```
> [2018-10-31.11:13:28] [Info] Compiling 'KeySearch.cl'...
> [2018-10-31.11:13:28] [Info] Error: C:\Users\Admin\AppData\Local\Temp\\OCL4956T3.cl:1:10: fatal error: 'sha256.cl' file not found
>                              #include "sha256.cl"
>                                       ^
>                              1 error generated.
> 
>                              error: Clang front-end compilation failed!
>                              Frontend phase failed compilation.
>                              Error: Compiling CL to IR
> ```
> Folder contents
> 
> ```
> D:\Mining\BitCrack 0.22
> 
> 31.10.2018  10:38    <DIR>          .
> 31.10.2018  10:38    <DIR>          ..
> 31.10.2018  08:32            68 096 AddrGen.exe
> 22.09.2018  01:52            13 007 Bitcrack.png
> 22.09.2018  02:27               855 BitCrack.txt
> 31.10.2018  08:35               143 btc.bat
> 23.10.2018  22:56       233 958 434 btc.txt
> 31.10.2018  08:32           151 552 clBitCrack.exe
> 31.10.2018  08:32         2 311 680 cuBitCrack.exe
> 31.10.2018  08:32            17 920 cudaInfo.exe
> 13.06.2018  07:53           368 128 cudart64_92.dll
> 11.10.2018  22:54               764 FAQ.txt
> 31.10.2018  08:33            10 964 keysearch.cl
> 15.06.2015  15:32           634 528 msvcp140.dll
> 31.10.2018  08:33            16 216 ripemd160.cl
> 31.10.2018  08:33            13 926 secp256k1.cl
> 31.10.2018  08:33            20 816 sha256.cl
> 23.06.2015  15:00            88 248 vcruntime140.dll
>               16 files    237 675 277 byte
>                2 folder  61 911 756 800 byte
> ```

The all cl files should be placed in the folder Temp,clBitCrack.exe reads and compiles them in this folder.

**Comment by PsyShark** [comment]
For nvidia cards there is a cudainfo utility, it says how many blocks the card has.
And using 'clBitCrack.exe --list-devices' shows the ID of the card and the name of Ellesmere.
How can I find out the number of blocks on AMD cards?

**Comment by PsyShark** [comment]
stake by spear, then we will be spear

**Comment by PsyShark** [comment]
method to poke our everything
