### ISSUE TITLE
increment changes in hex search

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#64]
i am looking increment changes as per switch, by default its uses +1

example
BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000000 

next is BitCrack.exe -s 
6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000001 
what i am looking user assign switch for increment add

example
BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000000 

then +500 increment
BitCrack.exe -s 6BBF8CCF80F8E184D1D300EF2CE45F7260E56766519C977831678F0000000501 

next +500 increment add into hex, not in digit

any solution

**Comment by hamnaz** [comment]
above function work in brainflayer
but brainflayer GPU not supported
in brainflayer function commands is 
-n 1/500
developer can study this case from brainflayer and can apply in bitcrack

**Comment by brichard19** [comment]
#68 created
