### ISSUE TITLE
Errr building BitCrack opencl (ubuntu 16.04)

### ISSUE THREAD

**Issue by RB61** [brichard19/BitCrack#70]
https://github.com/brichard19/BitCrack/blob/e70f26042f703edd57d15fa2324dc1b7493f3f80/CLKeySearchDevice/CLKeySearchDevice.cpp#L6

Hi
I'm getting this error using  
$ make BUILD_OPENCL=1

/home/racminer/BitCrack/lib/libCLKeySearchDevice.a(CLKeySearchDevice.o) : Dans la fonction « CLKeySearchDevice::CLKeySearchDevice(unsigned long, int, int, int) » :
CLKeySearchDevice.cpp:(.text+0x41c) : référence indéfinie vers « _bitcrack_cl »

where is bitcrack_cl.cpp ? how is it built in the pre-build event ?

thanks

**Comment by hamnaz** [comment]
first error at linux
any suggestion

![1111](https://user-images.githubusercontent.com/42878992/48309648-9315af00-e5a0-11e8-88b2-3057213698b3.jpeg)

**Comment by RB61** [comment]
You can get around this, just add
#include <cstring>
at the top of the file: clContext.cpp

**Comment by brichard19** [comment]
Hi,

I think something was not pushed. Sorry about that.  Try doing a pull and building again.

Thanks

**Comment by RB61** [comment]
Ooops
I did a pull, building again with
$make BUILD_OPENCL=1
gave this error:

In file included from cudaUtil.cpp:1:0:
cudaUtil.h:4:18: fatal error: cuda.h: Aucun fichier ou dossier de ce type
compilation terminated.
Makefile:6 : la recette pour la cible « all » a échouée
make[1]: *** [all] Erreur 1
make[1] : on quitte le répertoire « /home/racminer/BitCrack/cudaUtil »
Makefile:92 : la recette pour la cible « dir_cudautil » a échouée
make: *** [dir_cudautil] Erreur 2

??? seems that it is trying to install cuda option which I don't need ?

**Comment by RB61** [comment]
Ok

I removed dir_cudautil from
ARGETS=dir_addressutil dir_cmdparse dir_cryptoutil dir_keyfinderlib dir_keyfinder  dir_secp256k1lib dir_util dir_logger

I guess it is supposed to be here (only)
ifeq ($(BUILD_CUDA),1)
	TARGETS:=${TARGETS} dir_cudaKeySearchDevice dir_cudautil
endif

**Comment by RB61** [comment]
It is not over yet LOL
I tried this example:

racminer@mine:~/BitCrack/bin$ ./clBitCrack 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
[2018-11-11.22:49:44] [Info] Compression: compressed
[2018-11-11.22:49:44] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-11-11.22:49:44] [Info] Compiling OpenCL kernels...
[2018-11-11.22:49:57] [Info] Error: input.cl:38:9: warning: 'round' macro redefined
                             /usr/include/clc/math/round.h:2:9: note: previous definition is here
                             input.cl:1733:13: warning: implicit declaration of function 'printf' is invalid in OpenCL
                             input.cl:1735:9: warning: implicit declaration of function 'printf' is invalid in OpenCL
                             <unknown>:0:0: in function multiplyStepKernel void (i32, i32, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*): unsupported initializer for address space


My clinfo 

[clinfo.txt](https://github.com/brichard19/BitCrack/files/2569942/clinfo.txt)

**Comment by brichard19** [comment]
Good catch.

Unfortunately every OpenCL implementation is different i.e. nVidia doesn't have these errors. I don't have any AMD hardware right now :(

**Comment by RB61** [comment]
I commented out all printf in *.cl files (not used anyway) and got rid of warnings.
racminer@mine:~/BitCrack/bin$ ./clBitCrack 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
[2018-11-11.23:52:13] [Info] Compression: compressed
[2018-11-11.23:52:13] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-11-11.23:52:13] [Info] Compiling OpenCL kernels...
[2018-11-11.23:52:26] [Info] Error: input.cl:38:9: warning: 'round' macro redefined
                             /usr/include/clc/math/round.h:2:9: note: previous definition is here
                             <unknown>:0:0: in function multiplyStepKernel void (i32, i32, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*): unsupported initializer for address space

**Comment by brichard19** [comment]
Which device is this? You can try running with `--list-devices` and use `-d ` option to specify which device to use.

**Comment by RB61** [comment]
racminer@mine:~/BitCrack/bin$ ./clBitCrack -l
ID:     0
Name:   AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-36-generic, LLVM 6.0.0)
Memory: 8189MB

ID:     1
Name:   Ellesmere
Memory: 7684MB

**Comment by RB61** [comment]
I guess, we could close this issue now. It is still mysterious to me why 2 gpu's are detected as ID 0 and 1 both Ellesmere and my mobo has only one graphic card (Rx480 8Gb).
Thanks a lot.

**Comment by RB61** [comment]
That makes sense :+1:

**Comment by dhurst2590** [comment]
Could someone explain step by step how to run on Ubuntu for someone just learning Linux?
