### ISSUE TITLE
error: midlevel compiler failed build

### ISSUE THREAD

**Issue by voyagerlife** [brichard19/BitCrack#72]
I'm getting the following error when I start clBitCrack.exe on cmd with a simple address. Any idea?

[2018-11-15.23:27:27] [Info] Compression: compressed
[2018-11-15.23:27:27] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2018-11-15.23:27:27] [Info] Compiling OpenCL kernels...
[2018-11-15.23:27:28] [Info] Error: fcl build 1 succeeded.
                             error: Invalid user defined function being processed: ripemd160sha256()

                             error: midlevel compiler failed build.

**Comment by dem10** [comment]
(error: Invalid user defined function being processed)Maybe you wrote something wrong in the batch file?

**Comment by dem10** [comment]
error: Invalid user defined function being processed

**Comment by dem10** [comment]
you have been pointed out your mistake-error: Invalid user defined function being processed: ripemd160sha256()

**Comment by voyagerlife** [comment]
@dem10 I didn't get what you mean?

**Comment by brichard19** [comment]
Isn't OpenCL fun? :)

What hardware are you running?

**Comment by dem10** [comment]
> @ dem10 Я не понял, что вы имеете в виду?

you give little information-what system you have, the driver, that you have written in the batch file(address can retouch)

**Comment by brichard19** [comment]
Could be a bug in the OpenCL driver or something in the code.

**Comment by voyagerlife** [comment]
@brichard19 Intel HD graphics

**Comment by dem10** [comment]
> @ brichard19 Графика Intel HD
You have the latest driver of Intel,you have a x64 system?If so, you just have incompatible built-in graphics(perhaps the Intel driver does not give full opencl support).

**Comment by voyagerlife** [comment]
I drag and drop clBitCrack.exe to cmd and write the btc address in extension where I put "xxx"

Is something wrong with this command?

C:\Users\Voyager\Desktop\BitCrack-master\x64\Release\clBitCrack.exe xxx

**Comment by dem10** [comment]
> clBitCrack.exe

why download bitcrack master?Download clBitCrack.exe 0.23 and more you don't.Create a folder put there clBitCrack.exe create a text file in the folder and write there for example - (clBitCrack.exe -b 32 -t 256 -p 16 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH - o out.txt) save and rename the file, for example, in mycrack.bat

**Comment by voyagerlife** [comment]
I tried them all but it doesnt work and the same error.
Is it possible to run the software with amd ryzen cpu or amd radeon graphich card??
