### ISSUE TITLE
X Scanner

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#73]
Hi all
one more function could make this tool more attractive
already there is sequential search
if scanner is like to pick X and random value (0---f)applied at X,  
Example start key
1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
98d44e13f455d916674d38424d39e1cb01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
98d44e13f45xxxx6674d38424xxxxcb01b2a9132axxxxxxx97a6f8bb7fexx544
xxxxxxxxxx55d916674d38424d39e1cb01b2a9132aacbb7b97a6f8bb7feb2544

where x randomly changed for checking 
any suggestion

**Comment by hamnaz** [comment]
any work around this idea ?

**Comment by ogronome** [comment]
If you want something, do it. 
It is opensource.
But I doubt there is anyone else, who wants to loose speed on this useless operations.

**Comment by hamnaz** [comment]
for research and learn speed does not matter, some time speed not fruitfull, like rabit race :)
probabilities n possibilities always somewhere :)
