### ISSUE TITLE
not working in ubuntu 18.04

### ISSUE THREAD

**Issue by gsngsn123** [brichard19/BitCrack#78]
hi
iam trying this programme in ubuntu 18.04 when iam trying to build with make BUILD_OPENCL=1
nothing happening 
my device is quadro fx 3800

**Comment by brichard19** [comment]
What do you mean by "nothing happening"? Can you provide the output of make?

**Comment by gsngsn123** [comment]
![untitled](https://user-images.githubusercontent.com/33231545/48853235-0efbcc80-edd5-11e8-874a-eeffd037718a.png)
this is my windows iam trying this programme last 4 days but i dint got till now please help me 
in windows i tried cuda and opencl but in open cl instalize device and stoping perform i dont understant my open cl image below in windows
![untitled](https://user-images.githubusercontent.com/33231545/48853465-91848c00-edd5-11e8-8fa8-65a79b07cb09.png)

**Comment by gsngsn123** [comment]
please post open cl process its stoping when instaling device

**Comment by dem10** [comment]
> пожалуйста, сообщите открытому процессу cl его остановку при установке устройства

NVIDIA Quadro FX 3800-And the error you see?Error-Cuda driver version is insufficient for cuda runtime version

**Comment by gsngsn123** [comment]
but open cl version detected device pls help me that way

**Comment by dem10** [comment]
And why do you say that you have Ubuntu when the screens with Windows?

**Comment by dem10** [comment]
The Quadro FX 3800 GPU is no longer supported by CUDA 7.0 and beyond.The last CUDA version that supported that GPU was CUDA 6.5.And the minimum cuBitCrack is Cuda 8.Try to download it-https://developer.nvidia.com/opencl.If this does not help then you have a very old video card.
