### ISSUE TITLE
gtx 460 error

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#86]
new compile with opencl for gtx460  at debian linux strech 9.5 , cuda 9.2 not available for linux debian
and error on run, pls advice
![screenshot from 2018-11-26 18-01-02](https://user-images.githubusercontent.com/42878992/49015706-b8f8a180-f1a5-11e8-8361-fafb5e862645.png)

**Comment by hamnaz** [comment]
same time working on intel processor graphic , OK

[2018-11-26.19:07:25] [Info] Compression: both
[2018-11-26.19:07:25] [Info] Starting at: 5000000000000000000000000000000000000000000000000000000000000001
[2018-11-26.19:07:25] [Info] Ending at:   5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[2018-11-26.19:07:25] [Info] Counting by: 9223372036854775807
[2018-11-26.19:07:25] [Info] Compiling OpenCL kernels...
[2018-11-26.19:07:30] [Info] Initializing Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
[2018-11-26.19:07:30] [Info] Generating 262,144 starting points (10.0MB)
[2018-11-26.19:07:33] [Info] 10.0%
[2018-11-26.19:07:37] [Info] 20.0%
[2018-11-26.19:07:40] [Info] 30.0%
[2018-11-26.19:07:43] [Info] 40.0%
[2018-11-26.19:07:45] [Info] 50.0%
[2018-11-26.19:07:48] [Info] 60.0%
[2018-11-26.19:07:50] [Info] 70.0%
[2018-11-26.19:07:53] [Info] 80.0%
[2018-11-26.19:07:55] [Info] 90.0%
[2018-11-26.19:07:58] [Info] 100.0%
[2018-11-26.19:07:58] [Info] Done
[2018-11-26.19:07:58] [Info] Loading addresses from '1full.txt'
[2018-11-26.19:09:35] [Info] 18,451,882 addresses loaded (351.9MB)
Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (1,835,008 total) [00:00Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (3,670,016 total) [00:00Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (5,505,024 total) [00:00Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (7,340,032 total) [00:00Intel(R) Core(TM 528/7841MB | 18451882 targets 0.86 MKey/s (8,912,896 total) [00:00Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (10,747,904 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (12,582,912 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (14,417,920 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (16,252,928 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.87 MKey/s (17,825,792 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (19,660,800 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (21,495,808 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (23,330,816 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (25,165,824 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (27,000,832 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (28,835,840 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (30,670,848 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (32,505,856 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (34,340,864 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.84 MKey/s (35,913,728 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (37,748,736 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.85 MKey/s (39,321,600 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.86 MKey/s (40,894,464 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (42,729,472 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (44,564,480 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (46,399,488 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (48,234,496 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (50,069,504 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (51,904,512 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (53,739,520 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (55,574,528 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (57,409,536 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (59,244,544 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (61,079,552 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (62,914,560 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (64,749,568 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (66,584,576 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.87 MKey/s (68,157,440 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.88 MKey/s (69,992,448 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (71,827,456 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (73,662,464 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (75,497,472 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (77,332,480 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (79,167,488 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (81,002,496 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (82,837,504 total) [00:0Intel(R) Core(TM 528/7841MB | 18451882 targets 0.89 MKey/s (84,672,512 total)

**Comment by brichard19** [comment]
I'll add code to catch the error.


> cuda 9.2 not available for linux debian

If you're building on Linux, it's simple to use any CUDA version. In the `Makefile` change `CUDA_HOME` to point to your CUDA SDK directory.

**Comment by brichard19** [comment]
Hi,

Can you try reproducing the OpenCL error again with the latest build? I added an error check that should tell us what is going on.

**Comment by hamnaz** [comment]
![screenshot from 2018-11-28 14-38-27](https://user-images.githubusercontent.com/42878992/49142732-51646280-f31b-11e8-9648-9ceb3e0dc827.png)

**Comment by hamnaz** [comment]
![screenshot from 2018-11-28 14-37-58](https://user-images.githubusercontent.com/42878992/49142761-5e815180-f31b-11e8-9bd6-2dea119aef55.png)

**Comment by hamnaz** [comment]
i also check on same at samr vanitygen, i run oclvanitygen, its pickup gtx 460 gpu at opencl and run on 12mkey/s

**Comment by hamnaz** [comment]
more updates at windows 10
new windows 10
windows detect gtx 460 GPU and installed as display
cubitcrack.exe and clbitcrack.exe and other files from bitcrack release 0.26
samr vanitygen oclvanitygen64.exe
NO cuda install, nothing any other software install

Below pics will help to make more optimized ver by any devices at opencl platform
tomorrow I will install new hdd with Ubuntu and cuda, for check whats results by cuda

![530-half-speed](https://user-images.githubusercontent.com/42878992/49181581-9b921780-f30c-11e8-8945-cf24fd830dda.jpg)

**Comment by hamnaz** [comment]
![2](https://user-images.githubusercontent.com/42878992/49181606-aea4e780-f30c-11e8-81f5-8eed1c78cf86.jpg)

**Comment by hamnaz** [comment]
![3](https://user-images.githubusercontent.com/42878992/49181639-c41a1180-f30c-11e8-9871-a4ab9ec885be.jpg)

**Comment by hamnaz** [comment]
![4](https://user-images.githubusercontent.com/42878992/49181662-d1cf9700-f30c-11e8-831f-6029c0d77030.jpg)

**Comment by hamnaz** [comment]
![5](https://user-images.githubusercontent.com/42878992/49181684-df851c80-f30c-11e8-9b4d-c70508bd5ce1.jpg)

**Comment by hamnaz** [comment]
![6](https://user-images.githubusercontent.com/42878992/49181699-eb70de80-f30c-11e8-886b-74aa49cdda4e.jpg)

**Comment by hamnaz** [comment]
![7](https://user-images.githubusercontent.com/42878992/49182061-0ee85900-f30e-11e8-8a60-4e661ffb2da7.jpg)
