### ISSUE TITLE
Counting by:

### ISSUE THREAD

**Issue by hamnaz** [brichard19/BitCrack#87]
one more issue ( Counting by: )
1
i set --stride 72370055773322622139731865630429942408293740416025352524660990
result Counting by: 9223372036854775807

2
i set --stride 72370055773322622139731865630429942408293
result Counting by: 9223372036854775807

3
i set --stride 723
result Counting by: 723

4
i set --stride 99000
result Counting by: 99000

is there is some bug or wrong calc

**Comment by nbwolfpack** [comment]
It isn't a bug. The number that you are seeing for the first 2 is the maximum number for a 64 bit. The variable stride has a data type that can hold up to a 64 bit number. Hope this helps.

**Comment by brichard19** [comment]
I will fix it to read a 256-bit value.

**Comment by Coinpiet** [comment]
please can you explain me what i can do with --stride  i really dont understand that

**Comment by brichard19** [comment]
Hi,

The latest build will accept a full 256-bit value for `--stride`.

> please can you explain me what i can do with --stride i really dont understand that

Normally the program tests a key and then increments by 1. The `--stride` option tells the program to increment by key by another value. For example, `--stride 2` will tell the program to test keys 1, 3, 5, 7, 9, 11 ....  This was a feature requested by many users. One use for it would be to divide up work. One instance of the program could check keys 1, 3, 5, 7, 9....etc. and another instance could check 2, 4, 6, 8, 10... etc.

**Comment by Coinpiet** [comment]
oh ok now i undertsand it this is great but i have 5 Cards and all 5 Cards search on other keyspace in 58 bit space so mabey here it i snot good to use this stride ?
